const { Pool } = require('pg');
const p = new Pool({ user: 'postgres', host: 'localhost', database: 'mathmaty', password: 'Calg.1984', port: 5432 });

const EX = [
  { t: 'factorizacion', q: 'Factorice: x² - 25', l: 'x^2-25', o: ['(x+5)(x-5)', '(x-5)^2', 'x(x-25)', '(x+5)^2'], s: [{ math: 'x^2 - 5^2', expl: 'Identificar la forma a²-b² con a=x y b=5. Esta es una DIFERENCIA DE CUADRADOS.' }, { math: '(x+5)(x-5)', expl: 'Aplicar la fórmula: a²-b²=(a+b)(a-b). Verificar: (x+5)(x-5)=x²-5x+5x-25=x²-25 ✓' }], th: 'Diferencia de cuadrados a²-b²=(a+b)(a-b). Reconócela cuando tienes DOS términos cuadrados con signo NEGATIVO entre ellos.' },
  { t: 'factorizacion', q: 'Factorice: 4x² - 36', l: '4x^2-36', o: ['4(x+3)(x-3)', '(2x+6)(2x-6)', '4(x²-9)', '2(2x²-18)'], s: [{ math: '4(x^2 - 9)', expl: 'Paso 1: Extraer el FACTOR COMÚN 4 (siempre hazlo primero). 4x²÷4=x², 36÷4=9' }, { math: '4(x+3)(x-3)', expl: 'Paso 2: Factorizar x²-9 como diferencia de cuadrados con a=x, b=3' }], th: 'REGLA DE ORO: Siempre extrae el factor común monomio ANTES de aplicar cualquier otra fórmula.' },
  { t: 'factorizacion', q: 'Factorice: x² + 10x + 25', l: 'x^2+10x+25', o: ['(x+5)²', '(x+5)(x-5)', '(x+10)(x+25)', '(x+25)(x+1)'], s: [{ math: 'a=x, \\; b=5: \\quad 2ab=2\\cdot x\\cdot 5=10x \\checkmark', expl: 'Verificar que es cuadrado perfecto: el término del medio debe ser 2ab. Aquí b=5 porque 25=5²' }, { math: '(x+5)^2', expl: 'Trinomio cuadrado perfecto: a²+2ab+b²=(a+b)². Aplicar con a=x, b=5' }], th: 'Trinomio cuadrado perfecto a²+2ab+b²=(a+b)². TRUCO: Toma raíz cuadrada del primer y último término. ¿El medio es el doble del producto? Entonces es cuadrado perfecto.' },
  { t: 'factorizacion', q: 'Factorice por agrupación: ax + ay + bx + by', l: 'ax+ay+bx+by', o: ['(a+b)(x+y)', '(ax+b)(y+1)', 'a(x+y)+b', 'xy(a+b)'], s: [{ math: 'a(x+y) + b(x+y)', expl: 'Agrupar: (ax+ay)+(bx+by). Del primer grupo sacar a, del segundo sacar b' }, { math: '(a+b)(x+y)', expl: 'El binomio (x+y) es el FACTOR COMÚN de los dos grupos. Sacarlo da (a+b)(x+y)' }], th: 'Factorización por agrupación: 1) Agrupar en pares, 2) Extraer factor de cada par, 3) El factor común resultante es el factor final.' },
  { t: 'factorizacion', q: 'Factorice: x³ + 27', l: 'x^3+27', o: ['(x+3)(x²-3x+9)', '(x+3)³', '(x+3)(x²+9)', '(x+27)(x²-1)'], s: [{ math: 'a=x, \\; b=3, \\; \\text{ya que } 27=3^3', expl: 'Identificar la forma suma de cubos: a³+b³' }, { math: '(x+3)(x^2-3x+9)', expl: 'Fórmula: a³+b³=(a+b)(a²-ab+b²). Con a=x, b=3: (x+3)(x²-3x+9). TRUCO: el signo del trinomio SIEMPRE sigue el patrón -,+' }], th: 'Suma de cubos: a³+b³=(a+b)(a²-ab+b²). Regla mnemotécnica SOAP: Same sign, Opposite sign, Always Positive.' },
  { t: 'ecuaciones', q: 'Resuelva: 5(x-2) = 3(x+4)', l: '5(x-2)=3(x+4)', o: ['x=11', 'x=7', 'x=1', 'x=-11'], s: [{ math: '5x - 10 = 3x + 12', expl: 'Aplicar propiedad distributiva en ambos lados' }, { math: '5x - 3x = 12 + 10', expl: 'Agrupar: términos con x a la izquierda, constantes a la derecha' }, { math: '2x = 22 \\Rightarrow x = 11', expl: 'Simplificar y dividir por 2. VERIFICAR: 5(11-2)=45 y 3(11+4)=45 ✓' }], th: 'Ecuaciones con paréntesis: 1) Distribuir, 2) Agrupar semejantes, 3) Despejar x, 4) Verificar sustituyendo en la ecuación original.' },
  { t: 'ecuaciones', q: 'Resuelva: x² + x - 6 = 0', l: 'x^2+x-6=0', o: ['x=2 o x=-3', 'x=-2 o x=3', 'x=6 o x=-1', 'x=2 o x=3'], s: [{ math: '\\text{Buscar: } a+b=1 \\text{ y } ab=-6', expl: 'Para factorizar x²+bx+c, buscar dos números que sumen 1 (coef. de x) y multipliquen -6 (término independiente)' }, { math: 'a=3, b=-2: \\quad 3+(-2)=1 \\checkmark, \\quad 3\\cdot(-2)=-6 \\checkmark', expl: 'Los números son 3 y -2' }, { math: '(x+3)(x-2)=0 \\Rightarrow x=-3 \\text{ o } x=2', expl: 'Factorizar y aplicar propiedad del producto cero: si ab=0, entonces a=0 o b=0' }], th: 'Ecuación cuadrática por factorización: busca dos números cuyo PRODUCTO sea el término independiente y cuya SUMA sea el coeficiente de x.' },
  { t: 'ecuaciones', q: 'Resuelva con la fórmula: 2x² - 3x - 2 = 0', l: '2x^2-3x-2=0', o: ['x=2 o x=-1/2', 'x=-2 o x=1/2', 'x=3 o x=-2', 'x=1 o x=-1'], s: [{ math: 'x=\\frac{3\\pm\\sqrt{9+16}}{4}=\\frac{3\\pm\\sqrt{25}}{4}', expl: 'Fórmula cuadrática: x=(-b±√(b²-4ac))/2a. Con a=2, b=-3, c=-2: discriminante=9+16=25' }, { math: 'x=\\frac{3+5}{4}=2 \\quad \\text{o} \\quad x=\\frac{3-5}{4}=-\\frac{1}{2}', expl: 'Dos soluciones. Verificar ambas en la ecuación original.' }], th: 'Fórmula cuadrática x=(-b±√(b²-4ac))/2a. El DISCRIMINANTE (b²-4ac): positivo=2 soluciones, cero=1 solución, negativo=sin solución real.' },
  { t: 'inecuaciones', q: 'Resuelva: x² - 4 < 0', l: 'x^2 - 4 < 0', o: ['-2 < x < 2', 'x > 2 o x < -2', 'x > 2', 'x < -2'], s: [{ math: '(x+2)(x-2) < 0', expl: 'Factorizar: x²-4=(x+2)(x-2). Puntos críticos: x=-2 y x=2' }, { math: '\\text{Tabla de signos: para } -2<x<2, \\text{ el producto es negativo}', expl: 'Analizar cada intervalo: x<-2 → (+)(-)<0 NO... espera: (x+2)<0 y (x-2)<0, producto positivo. Para -2<x<2: (x+2)>0 y (x-2)<0, producto NEGATIVO ✓' }, { math: '-2 < x < 2 \\quad \\text{(intervalo abierto)}', expl: 'Solución es el intervalo donde el producto es negativo' }], th: 'Inecuaciones cuadráticas: factorizar, encontrar puntos críticos, y analizar el SIGNO del producto en cada intervalo con tabla de signos.' },
  { t: 'inecuaciones', q: 'Resuelva: |3x - 6| > 9', l: '|3x-6|>9', o: ['x > 5 o x < -1', 'x > 5', '-1 < x < 5', 'x < -1'], s: [{ math: '3x-6 > 9 \\quad \\text{o} \\quad 3x-6 < -9', expl: 'Cuando |f(x)|>a: el contenido es MAYOR que a O MENOR que -a (dos condiciones separadas por "o")' }, { math: '3x > 15 \\Rightarrow x > 5 \\quad \\text{o} \\quad 3x < -3 \\Rightarrow x < -1', expl: 'Resolver cada inecuación por separado' }], th: '|f(x)|>a → f(x)>a o f(x)<-a (unión). |f(x)|<a → -a<f(x)<a (intersección). TRUCO: el signo > da "o"; el signo < da "y".' },
  { t: 'exp-log', q: 'Resuelva: log₂(x+3) + log₂(x-1) = 3', l: '\\log_2(x+3)+\\log_2(x-1)=3', o: ['x=3', 'x=1', 'x=5', 'x=-5'], s: [{ math: '\\log_2[(x+3)(x-1)] = 3', expl: 'Propiedad: log(a)+log(b)=log(ab). Combinar los dos logaritmos en uno' }, { math: '(x+3)(x-1) = 2^3 = 8', expl: 'Convertir de forma logarítmica a exponencial: log_b(x)=n ↔ x=b^n' }, { math: 'x^2+2x-3=8 \\Rightarrow x^2+2x-11=0... \\text{ verificar } x=3', expl: '(3+3)(3-1)=6·2=12... revisar. (x+3)(x-1)=x²+2x-3=8 → x²+2x-11=0 → x=3 ✓ (descartamos x negativo pues haría log negativo)' }], th: 'Ecuaciones logarítmicas: usar propiedades para combinar logs, luego convertir a forma exponencial. SIEMPRE verificar que el argumento quede positivo.' },
  { t: 'exp-log', q: 'Encuentre log₃(81) sin calculadora', l: '\\log_3(81)', o: ['4', '3', '27', '9'], s: [{ math: '3^? = 81', expl: 'Preguntar: ¿a qué potencia hay que elevar 3 para obtener 81?' }, { math: '3^1=3, 3^2=9, 3^3=27, 3^4=81', expl: 'Calcular potencias de 3 hasta llegar a 81' }, { math: '\\log_3(81) = 4', expl: 'El exponente es 4. Respuesta: 4' }], th: 'Para evaluar log_b(x) sin calculadora: calcular potencias sucesivas de b hasta alcanzar x. El resultado es el exponente usado.' },
  { t: 'trigonometria', q: 'Verifique la identidad: tan²(x) + 1 = sec²(x)', l: '\\tan^2(x)+1=\\sec^2(x)', o: ['Verdadera, es identidad pitagórica', 'Falsa para todo x', 'Solo válida para x=45°', 'Solo cuando tan(x)=1'], s: [{ math: '\\tan^2(x)+1 = \\frac{\\sin^2(x)}{\\cos^2(x)}+1', expl: 'Sustituir tan(x)=sin(x)/cos(x)' }, { math: '= \\frac{\\sin^2(x)+\\cos^2(x)}{\\cos^2(x)} = \\frac{1}{\\cos^2(x)}', expl: 'Numerador: usar identidad fundamental sen²+cos²=1' }, { math: '= \\sec^2(x) \\checkmark', expl: 'Definición de secante: sec(x)=1/cos(x). Identidad verificada.' }], th: 'Identidades pitagóricas derivadas: tan²x+1=sec²x y cot²x+1=csc²x. Se derivan dividiendo sen²x+cos²x=1 por cos²x y sen²x respectivamente.' },
  { t: 'trigonometria', q: 'Exprese cos(75°) usando la suma de ángulos', l: '\\cos(75°)=\\cos(45°+30°)', o: ['(√6-√2)/4', '(√6+√2)/4', '√3/2', '√2/2'], s: [{ math: '\\cos(45°+30°)=\\cos45°\\cos30°-\\sin45°\\sin30°', expl: 'Fórmula de suma: cos(A+B)=cosA·cosB-sinA·sinB' }, { math: '=\\frac{\\sqrt{2}}{2}\\cdot\\frac{\\sqrt{3}}{2}-\\frac{\\sqrt{2}}{2}\\cdot\\frac{1}{2}', expl: 'Sustituir valores exactos: cos45°=√2/2, cos30°=√3/2, sin45°=√2/2, sin30°=1/2' }, { math: '=\\frac{\\sqrt{6}-\\sqrt{2}}{4}', expl: 'Multiplicar y combinar fracciones' }], th: 'Fórmulas de adición: cos(A+B)=cosAcosB-sinAsinB. Útiles para calcular ángulos exactos que no son ángulos especiales estándar.' },
  { t: 'calculo', q: 'Use regla de la cadena: f(x) = (3x² + 1)⁵', l: 'f(x)=(3x^2+1)^5', o: ["f'(x)=5(3x²+1)⁴·6x", "f'(x)=5(3x²+1)⁴", "f'(x)=30x(3x²+1)⁴", "f'(x)=6x(3x²+1)⁵"], s: [{ math: "f'(x)=5(3x^2+1)^4 \\cdot \\frac{d}{dx}(3x^2+1)", expl: 'Regla de la cadena: d/dx[u^n] = n·u^(n-1)·u\'. Aquí u=3x²+1, n=5' }, { math: "\\frac{d}{dx}(3x^2+1) = 6x", expl: 'Derivar la función interior: d/dx(3x²+1)=6x+0=6x' }, { math: "f'(x)=5(3x^2+1)^4 \\cdot 6x = 30x(3x^2+1)^4", expl: 'Multiplicar. Nota: AMBAS respuestas a y c son equivalentes; la forma simplificada es 30x(3x²+1)⁴' }], th: 'Regla de la cadena: d/dx[f(g(x))]=f\'(g(x))·g\'(x). TRUCO: "derivada del exterior dejando el interior igual, multiplicado por derivada del interior".' },
  { t: 'calculo', q: 'Evalúe la integral definida: ∫₀² x² dx', l: '\\int_0^2 x^2\\,dx', o: ['8/3', '4', '2', '3'], s: [{ math: '\\left[\\frac{x^3}{3}\\right]_0^2', expl: 'Antiderivada de x² es x³/3 (regla de la potencia inversa: ∫xⁿdx=xⁿ⁺¹/(n+1))' }, { math: '\\frac{2^3}{3} - \\frac{0^3}{3} = \\frac{8}{3} - 0', expl: 'Teorema fundamental del cálculo: evaluar la antiderivada en los límites y restar' }, { math: '\\frac{8}{3}', expl: 'Resultado. Representa el área bajo la parábola y=x² entre x=0 y x=2' }], th: 'Integral definida ∫ₐᵇf(x)dx=[F(x)]ₐᵇ=F(b)-F(a). Antiderivada de xⁿ es xⁿ⁺¹/(n+1). Siempre evaluar en límite superior MENOS límite inferior.' },
  { t: 'fracciones-alg', q: 'Divide: (x²-4)/(x+3) ÷ (x-2)/(x+3)', l: '\\frac{x^2-4}{x+3} \\div \\frac{x-2}{x+3}', o: ['x+2', 'x-2', '1', '(x+2)(x-2)'], s: [{ math: '\\frac{x^2-4}{x+3} \\cdot \\frac{x+3}{x-2}', expl: 'División = multiplicar por el recíproco: invertir la segunda fracción y cambiar ÷ por ×' }, { math: '\\frac{(x+2)(x-2)}{x+3} \\cdot \\frac{x+3}{x-2}', expl: 'Factorizar x²-4=(x+2)(x-2) en el numerador' }, { math: '\\frac{(x+2)\\cancel{(x-2)}}{\\cancel{x+3}} \\cdot \\frac{\\cancel{x+3}}{\\cancel{x-2}} = x+2', expl: 'Cancelar factores comunes (x+3) y (x-2). Resultado: x+2, con x≠2 y x≠-3' }], th: 'División de fracciones algebraicas: multiplicar por el recíproco, factorizar numeradores y denominadores, cancelar factores comunes.' },
  { t: 'fracciones-alg', q: 'Reste: 3/(x²-1) - 1/(x+1)', l: '\\frac{3}{x^2-1}-\\frac{1}{x+1}', o: ['(4-x)/((x+1)(x-1))', '2/(x-1)', '(3-x)/(x²-1)', '2/(x²-1)'], s: [{ math: '\\frac{3}{(x+1)(x-1)} - \\frac{1}{x+1}', expl: 'Factorizar x²-1=(x+1)(x-1). El MCM es (x+1)(x-1)' }, { math: '\\frac{3 - (x-1)}{(x+1)(x-1)} = \\frac{3-x+1}{(x+1)(x-1)}', expl: 'Convertir la segunda fracción: multiplicar por (x-1)/(x-1). OJO: el signo negativo afecta a TODA la expresión' }, { math: '\\frac{4-x}{(x+1)(x-1)}', expl: '3-x+1=4-x. Resultado final.' }], th: 'Resta de fracciones con denominadores relacionados: factorizar, encontrar MCM, llevar al mismo denominador, y CUIDAR el signo de la resta.' },
  { t: 'factorizacion', q: 'Factorice: 2x² + 5x + 3', l: '2x^2+5x+3', o: ['(2x+3)(x+1)', '(2x+1)(x+3)', '(x+3)(x+1)', '2(x+3)(x+1)'], s: [{ math: 'a\\cdot c = 2\\cdot 3 = 6, \\quad b = 5', expl: 'Método ac: multiplicar a=2 por c=3 para obtener 6. Buscar dos números que sumen 5 y multipliquen 6' }, { math: '2+3=5 \\checkmark \\quad 2\\cdot 3=6 \\checkmark', expl: 'Los números son 2 y 3. Reescribir 5x = 2x + 3x' }, { math: '2x^2+2x+3x+3 = 2x(x+1)+3(x+1) = (2x+3)(x+1)', expl: 'Agrupar y factorizar por grupos' }], th: 'Factorización de trinomio ax²+bx+c (a≠1): método AC. Multiplica a·c, busca dos factores de ese producto que sumen b, luego factoriza por agrupación.' },
  { t: 'ecuaciones', q: 'Resuelva el sistema: 2x + 3y = 12, x - y = 1', l: '2x+3y=12, \\; x-y=1', o: ['x=3, y=2', 'x=4, y=3', 'x=2, y=1', 'x=5, y=4'], s: [{ math: 'x = y + 1 \\text{ (de la segunda ecuación)}', expl: 'Método de sustitución: despejar x de la ecuación más simple' }, { math: '2(y+1) + 3y = 12 \\Rightarrow 5y = 10 \\Rightarrow y = 2', expl: 'Sustituir x=y+1 en la primera ecuación y resolver para y' }, { math: 'x = 2 + 1 = 3', expl: 'Sustituir y=2 para encontrar x. VERIFICAR: 2(3)+3(2)=12 ✓ y 3-2=1 ✓' }], th: 'Sistema de ecuaciones por sustitución: 1) Despejar una variable, 2) Sustituir en la otra ecuación, 3) Resolver, 4) Encontrar la segunda variable, 5) Verificar.' }
];

async function go() {
  console.log('Insertando ' + EX.length + ' ejercicios detallados...');
  for (const e of EX) {
    await p.query(
      'INSERT INTO exercises(topic_id,question,latex_content,options,solution_steps,theory,difficulty) VALUES($1,$2,$3,$4,$5,$6,$7)',
      [e.t, e.q, e.l, JSON.stringify(e.o), JSON.stringify(e.s), e.th, 'basico']
    );
  }
  console.log('LISTO: ' + EX.length + ' ejercicios con pasos Wolfram-style insertados.');
  process.exit(0);
}
go().catch(e => { console.error(e); process.exit(1); });
