process.env.NODE_TLS_REJECT_UNAUTHORIZED='0';
const{Pool}=require('pg');
const p=new Pool({connectionString:process.env.DATABASE_URL||'postgresql://neondb_owner:npg_x5NnjheXrb4H@ep-broad-wildflower-aq3he37e-pooler.c-8.us-east.1.aws.neon.tech/mathmaty?sslmode=require',ssl:{rejectUnauthorized:false}});
const S='gen-flash-v23';const A='generacion-programatica';

function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function mkOpts(c,o){let all=shuffle([c,...o]);return{o:all,ci:all.indexOf(c)};}

const temas=[
  // === SISTEMAS DE ECUACIONES (20) ===
  {t:'sistemas-ecuaciones',n:'9-11',q:'Resuelve: x+y=5, x-y=1',c:'x=3,y=2',o:['x=2,y=3','x=4,y=1','x=1,y=4']},
  {t:'sistemas-ecuaciones',n:'9-11',q:'Resuelve: 2x+y=7, x-y=2',c:'x=3,y=1',o:['x=2,y=3','x=1,y=5','x=4,y=-1']},
  {t:'sistemas-ecuaciones',n:'9-11',q:'Resuelve: 3x+2y=12, x-y=1',c:'x=2.8,y=1.8',o:['x=3,y=1.5','x=2,y=3','x=4,y=0']},
  {t:'sistemas-ecuaciones',n:'9-11',q:'Resuelve: x+y=10, 2x-y=5',c:'x=5,y=5',o:['x=4,y=6','x=6,y=4','x=3,y=7']},
  {t:'sistemas-ecuaciones',n:'9-11',q:'El metodo de sustitucion consiste en:',c:'Despejar una variable y reemplazar',o:['Sumar ecuaciones','Multiplicar ecuaciones','Igualar coeficientes']},
  {t:'sistemas-ecuaciones',n:'9-11',q:'Si un sistema tiene una unica solucion, las rectas son:',c:'Secantes',o:['Paralelas','Coincidentes','Perpendiculares']},
  {t:'sistemas-ecuaciones',n:'9-11',q:'Si un sistema no tiene solucion, las rectas son:',c:'Paralelas',o:['Secantes','Coincidentes','Perpendiculares']},
  {t:'sistemas-ecuaciones',n:'9-11',q:'Si un sistema tiene infinitas soluciones, las rectas son:',c:'Coincidentes',o:['Paralelas','Secantes','Perpendiculares']},
  {t:'sistemas-ecuaciones',n:'9-11',q:'Resuelve: 4x+3y=18, 2x-y=4',c:'x=3,y=2',o:['x=2,y=3.33','x=4,y=0.67','x=5,y=-0.67']},
  {t:'sistemas-ecuaciones',n:'9-11',q:'Resuelve: x+y=8, x-y=8',c:'x=8,y=0',o:['x=0,y=8','x=4,y=4','x=8,y=8']},
  {t:'sistemas-ecuaciones',n:'9-11',q:'Resuelve: 5x+2y=20, 3x-y=1',c:'x=2,y=5',o:['x=3,y=2.5','x=4,y=0','x=1,y=7.5']},
  {t:'sistemas-ecuaciones',n:'9-11',q:'2x+3y=13, 4x-y=5. x+y=',c:'6',o:['5','7','8']},
  {t:'sistemas-ecuaciones',n:'9-11',q:'El determinante de [[a,b],[c,d]] es:',c:'ad-bc',o:['ab-cd','ac-bd','ad+bc']},
  {t:'sistemas-ecuaciones',n:'9-11',q:'Resuelve por determinantes: 2x+y=5, x-3y=6',c:'x=3,y=-1',o:['x=2,y=1','x=1,y=3','x=4,y=-3']},
  {t:'sistemas-ecuaciones',n:'9-11',q:'Resuelve: (1/x)+(1/y)=3/4, x=y',c:'x=8/3,y=8/3',o:['x=2,y=2','x=4,y=4','x=4/3,y=4/3']},
  {t:'sistemas-ecuaciones',n:'9-11',q:'Un sistema 2x2 tiene solucion unica si:',c:'det != 0',o:['det = 0','det > 0','det < 0']},
  {t:'sistemas-ecuaciones',n:'9-11',q:'Resuelve: 6x-2y=10, 3x-2y=4',c:'x=2,y=1',o:['x=1,y=-2','x=3,y=4','x=0,y=-5']},
  {t:'sistemas-ecuaciones',n:'9-11',q:'Resuelve: 2x+5y=19, 6x-5y=-3',c:'x=2,y=3',o:['x=4,y=2.2','x=1,y=3.4','x=3,y=2.6']},
  {t:'sistemas-ecuaciones',n:'9-11',q:'x+y=a, x-y=b. La solucion es:',c:'x=(a+b)/2, y=(a-b)/2',o:['x=(a-b)/2, y=(a+b)/2','x=a+b, y=a-b','x=a/2, y=b/2']},
  {t:'sistemas-ecuaciones',n:'9-11',q:'Tres numeros suman 15. El primero mas el segundo es 10. El primero menos el tercero es 0.',c:'5,5,5',o:['3,7,5','6,4,5','4,6,5']},

  // === PLANO CARTESIANO (20) ===
  {t:'plano-cartesiano',n:'7-10',q:'El punto (0,0) se llama:',c:'Origen',o:['Eje X','Eje Y','Vertice']},
  {t:'plano-cartesiano',n:'7-10',q:'La distancia entre (1,2) y (4,6) es:',c:'5',o:['3','4','7']},
  {t:'plano-cartesiano',n:'7-10',q:'La distancia entre (-2,3) y (2,-3) es:',c:'√52=2√13',o:['10','8','√20=2√5']},
  {t:'plano-cartesiano',n:'7-10',q:'El punto medio entre (1,5) y (7,1) es:',c:'(4,3)',o:['(3,2)','(5,3)','(4,2)']},
  {t:'plano-cartesiano',n:'7-10',q:'La pendiente de la recta que pasa por (1,2) y (3,6) es:',c:'2',o:['1/2','3','4']},
  {t:'plano-cartesiano',n:'7-10',q:'La pendiente de una recta horizontal es:',c:'0',o:['1','∞','-1']},
  {t:'plano-cartesiano',n:'7-10',q:'La pendiente de una recta vertical es:',c:'Indefinida',o:['0','1','∞']},
  {t:'plano-cartesiano',n:'7-10',q:'La ecuacion y = 2x + 3 tiene pendiente:',c:'2',o:['3','-2','1/2']},
  {t:'plano-cartesiano',n:'7-10',q:'La ecuacion y = 2x + 3 tiene intercepto en y:',c:'3',o:['2','-3','(0,2)']},
  {t:'plano-cartesiano',n:'7-10',q:'Dos rectas son paralelas si:',c:'Tienen igual pendiente',o:['Se intersectan','Pendiente producto=-1','Misma ecuacion']},
  {t:'plano-cartesiano',n:'7-10',q:'Dos rectas son perpendiculares si:',c:'m1*m2 = -1',o:['m1=m2','m1+m2=0','m1-m2=1']},
  {t:'plano-cartesiano',n:'7-10',q:'El punto (3,-4) esta en el cuadrante:',c:'IV',o:['I','II','III']},
  {t:'plano-cartesiano',n:'7-10',q:'El punto (-5,2) esta en el cuadrante:',c:'II',o:['I','III','IV']},
  {t:'plano-cartesiano',n:'7-10',q:'f(x)=3x-1. f(2)=',c:'5',o:['3','7','4']},
  {t:'plano-cartesiano',n:'7-10',q:'f(x)=x^2+1. f(-3)=',c:'10',o:['8','7','9']},
  {t:'plano-cartesiano',n:'7-10',q:'El dominio de f(x)=√(x-2) es:',c:'x >= 2',o:['x > 2','x <= 2','Todos los reales']},
  {t:'plano-cartesiano',n:'7-10',q:'El rango de f(x)=x^2 es:',c:'y >= 0',o:['y > 0','Todos los reales','y <= 0']},
  {t:'plano-cartesiano',n:'7-10',q:'La grafica de f(x)=x^2 es:',c:'Parabola',o:['Recta','Circunferencia','Hiperbola']},
  {t:'plano-cartesiano',n:'7-10',q:'Distancia de (-4,-3) al origen:',c:'5',o:['4','3','7']},
  {t:'plano-cartesiano',n:'7-10',q:'La funcion f(x)=mx+b es:',c:'Lineal',o:['Cuadratica','Cubica','Exponencial']},

  // === MCM Y MCD (20) ===
  {t:'mcm-mcd',n:'prim-7',q:'MCD(12,18)=',c:'6',o:['3','2','36']},
  {t:'mcm-mcd',n:'prim-7',q:'MCM(12,18)=',c:'36',o:['6','12','24']},
  {t:'mcm-mcd',n:'prim-7',q:'MCD(24,36)=',c:'12',o:['6','18','72']},
  {t:'mcm-mcd',n:'prim-7',q:'MCM(24,36)=',c:'72',o:['12','24','48']},
  {t:'mcm-mcd',n:'prim-7',q:'MCD(15,25)=',c:'5',o:['3','1','75']},
  {t:'mcm-mcd',n:'prim-7',q:'MCM(15,25)=',c:'75',o:['5','15','25']},
  {t:'mcm-mcd',n:'prim-7',q:'MCD(7,13)=',c:'1',o:['7','13','91']},
  {t:'mcm-mcd',n:'prim-7',q:'MCM(7,13)=',c:'91',o:['7','13','20']},
  {t:'mcm-mcd',n:'prim-7',q:'MCD(48,60)=',c:'12',o:['6','24','240']},
  {t:'mcm-mcd',n:'prim-7',q:'MCM(48,60)=',c:'240',o:['12','48','120']},
  {t:'mcm-mcd',n:'prim-7',q:'Dos numeros con MCD=1 se llaman:',c:'Coprimos',o:['Primos','Compuestos','Pares']},
  {t:'mcm-mcd',n:'prim-7',q:'MCM(a,b) * MCD(a,b) =',c:'a * b',o:['a + b','a - b','a / b']},
  {t:'mcm-mcd',n:'prim-7',q:'MCD(36,48,60)=',c:'12',o:['6','24','720']},
  {t:'mcm-mcd',n:'prim-7',q:'MCM(36,48,60)=',c:'720',o:['12','120','240']},
  {t:'mcm-mcd',n:'prim-7',q:'MCD(100,75)=',c:'25',o:['5','50','300']},
  {t:'mcm-mcd',n:'prim-7',q:'MCM(100,75)=',c:'300',o:['25','100','7500']},
  {t:'mcm-mcd',n:'prim-7',q:'Si MCM(a,b)=ab, entonces MCD(a,b)=',c:'1',o:['ab','a','b']},
  {t:'mcm-mcd',n:'prim-7',q:'El MCD de 8 y 12 es 4 porque:',c:'4 divide a ambos y es el mayor',o:['4 es multiplo de ambos','8/4=2','12/4=3']},
  {t:'mcm-mcd',n:'prim-7',q:'MCM(5,10,15)=',c:'30',o:['5','15','150']},
  {t:'mcm-mcd',n:'prim-7',q:'MCD(5,10,15)=',c:'5',o:['1','10','15']},

  // === PORCENTAJES (20) ===
  {t:'porcentajes',n:'prim-8',q:'El 20% de 80 es:',c:'16',o:['8','20','40']},
  {t:'porcentajes',n:'prim-8',q:'El 15% de 200 es:',c:'30',o:['15','20','300']},
  {t:'porcentajes',n:'prim-8',q:'¿Que porcentaje de 50 es 10?',c:'20%',o:['10%','25%','50%']},
  {t:'porcentajes',n:'prim-8',q:'¿Que porcentaje de 200 es 40?',c:'20%',o:['10%','40%','25%']},
  {t:'porcentajes',n:'prim-8',q:'30% de 90 =',c:'27',o:['30','3','9']},
  {t:'porcentajes',n:'prim-8',q:'Un producto cuesta 500 y tiene 15% descuento. Precio final:',c:'425',o:['485','500','75']},
  {t:'porcentajes',n:'prim-8',q:'Un producto cuesta 200 y tiene 10% de aumento. Precio final:',c:'220',o:['210','200','190']},
  {t:'porcentajes',n:'prim-8',q:'Si 25% de un numero es 30, el numero es:',c:'120',o:['60','75','150']},
  {t:'porcentajes',n:'prim-8',q:'Convertir 3/4 a porcentaje:',c:'75%',o:['50%','25%','100%']},
  {t:'porcentajes',n:'prim-8',q:'Convertir 0.35 a porcentaje:',c:'35%',o:['3.5%','0.35%','350%']},
  {t:'porcentajes',n:'prim-8',q:'45% de 400 =',c:'180',o:['45','90','200']},
  {t:'porcentajes',n:'prim-8',q:'75% de 120 =',c:'90',o:['75','30','60']},
  {t:'porcentajes',n:'prim-8',q:'120% de 50 =',c:'60',o:['50','70','100']},
  {t:'porcentajes',n:'prim-8',q:'Un articulo cuesta 80, se vende a 100. Ganancia %:',c:'25%',o:['20%','80%','125%']},
  {t:'porcentajes',n:'prim-8',q:'Si 60 estudiantes representan el 30% del total, el total es:',c:'200',o:['60','180','300']},
  {t:'porcentajes',n:'prim-8',q:'En un 20% de descuento, por cada 100 se pagan:',c:'80',o:['20','100','120']},
  {t:'porcentajes',n:'prim-8',q:'150 es el 50% de:',c:'300',o:['75','150','100']},
  {t:'porcentajes',n:'prim-8',q:'35% escrito como decimal es:',c:'0.35',o:['3.5','0.035','35.0']},
  {t:'porcentajes',n:'prim-8',q:'El interes simple de 1000 al 5% anual por 2 anos es:',c:'100',o:['50','500','200']},
  {t:'porcentajes',n:'prim-8',q:'Si la poblacion crece 3% anual y es 10000, tras un ano sera:',c:'10300',o:['10030','13000','10003']},

  // === GEOMETRIA (20) ===
  {t:'geometria',n:'prim-10',q:'El area de un rectangulo de base 5 y altura 3 es:',c:'15',o:['8','16','10']},
  {t:'geometria',n:'prim-10',q:'El perimetro de un cuadrado de lado 6 es:',c:'24',o:['12','36','18']},
  {t:'geometria',n:'prim-10',q:'El area de un triangulo de base 8 y altura 5 es:',c:'20',o:['13','40','25']},
  {t:'geometria',n:'prim-10',q:'El area de un circulo de radio 3 es:',c:'9π',o:['6π','3π','12π']},
  {t:'geometria',n:'prim-10',q:'El perimetro de un circulo de radio 4 es:',c:'8π',o:['4π','16π','2π']},
  {t:'geometria',n:'prim-10',q:'Un triangulo rectangulo tiene catetos 3 y 4. Hipotenusa:',c:'5',o:['6','7','25']},
  {t:'geometria',n:'prim-10',q:'Un triangulo rectangulo tiene catetos 5 y 12. Hipotenusa:',c:'13',o:['14','15','17']},
  {t:'geometria',n:'prim-10',q:'El volumen de un cubo de lado 3 es:',c:'27',o:['9','12','18']},
  {t:'geometria',n:'prim-10',q:'El area de un cuadrado de diagonal 4√2 es:',c:'16',o:['8','32','4']},
  {t:'geometria',n:'prim-10',q:'La suma de angulos internos de un triangulo es:',c:'180°',o:['90°','360°','270°']},
  {t:'geometria',n:'prim-10',q:'La suma de angulos internos de un cuadrilatero es:',c:'360°',o:['180°','270°','540°']},
  {t:'geometria',n:'prim-10',q:'Un triangulo con todos sus lados iguales es:',c:'Equilatero',o:['Isosceles','Escaleno','Rectangulo']},
  {t:'geometria',n:'prim-10',q:'Un triangulo con dos lados iguales es:',c:'Isosceles',o:['Equilatero','Escaleno','Rectangulo']},
  {t:'geometria',n:'prim-10',q:'El area de un trapecio de bases 6 y 4, altura 3 es:',c:'15',o:['12','30','20']},
  {t:'geometria',n:'prim-10',q:'La longitud de una circunferencia de radio 5 es:',c:'10π',o:['5π','25π','2π']},
  {t:'geometria',n:'prim-10',q:'Un angulo recto mide:',c:'90°',o:['45°','180°','360°']},
  {t:'geometria',n:'prim-10',q:'Dos angulos complementarios suman:',c:'90°',o:['180°','360°','45°']},
  {t:'geometria',n:'prim-10',q:'Dos angulos suplementarios suman:',c:'180°',o:['90°','360°','270°']},
  {t:'geometria',n:'prim-10',q:'El volumen de una esfera de radio 3 es:',c:'36π',o:['27π','9π','12π']},
  {t:'geometria',n:'prim-10',q:'El area lateral de un cilindro de radio 2 y altura 5 es:',c:'20π',o:['10π','40π','14π']},

  // === RAZONES Y PROPORCIONES (20) ===
  {t:'razones-proporciones',n:'prim-9',q:'La razon de 4 a 5 es:',c:'4/5',o:['5/4','4:4','1.25']},
  {t:'razones-proporciones',n:'prim-9',q:'La razon 3:5 = 6:x. x =',c:'10',o:['5','15','30']},
  {t:'razones-proporciones',n:'prim-9',q:'Si 2:3 = 8:x, entonces x =',c:'12',o:['6','4','24']},
  {t:'razones-proporciones',n:'prim-9',q:'3:4 = x:16. x =',c:'12',o:['8','9','16']},
  {t:'razones-proporciones',n:'prim-9',q:'Si 5 libros cuestan 75, 8 libros cuestan:',c:'120',o:['100','150','140']},
  {t:'razones-proporciones',n:'prim-9',q:'Si 3 obreros hacen un trabajo en 12 dias, 6 obreros lo hacen en:',c:'6 dias',o:['24 dias','12 dias','3 dias']},
  {t:'razones-proporciones',n:'prim-9',q:'Si 4 obreros hacen una pared en 6 horas, 2 obreros tardan:',c:'12 horas',o:['3 horas','6 horas','8 horas']},
  {t:'razones-proporciones',n:'prim-9',q:'Si 10 km son 6.2 millas, 25 km son:',c:'15.5 millas',o:['12.4 millas','20 millas','31 millas']},
  {t:'razones-proporciones',n:'prim-9',q:'Dos variables son directamente proporcionales si:',c:'Su cociente es constante',o:['Su suma es constante','Su producto es constante','Su diferencia es constante']},
  {t:'razones-proporciones',n:'prim-9',q:'Dos variables son inversamente proporcionales si:',c:'Su producto es constante',o:['Su cociente es constante','Su suma es constante','Su diferencia es constante']},
  {t:'razones-proporciones',n:'prim-9',q:'Si A es directamente proporcional a B, y A=10 cuando B=2, A cuando B=5 es:',c:'25',o:['10','4','50']},
  {t:'razones-proporciones',n:'prim-9',q:'Si A es inversamente proporcional a B, y A=12 cuando B=3, A cuando B=6 es:',c:'6',o:['12','24','3']},
  {t:'razones-proporciones',n:'prim-9',q:'La razon entre 2 km y 500 m es:',c:'4:1',o:['2:5','1:4','5:2']},
  {t:'razones-proporciones',n:'prim-9',q:'Repartir 40 en proporcion 3:5. Las partes son:',c:'15 y 25',o:['20 y 20','10 y 30','12 y 28']},
  {t:'razones-proporciones',n:'prim-9',q:'Una escala 1:100 significa:',c:'1 cm = 100 cm reales',o:['1 cm = 1 m real','100 cm = 1 cm real','1:100 no es escala']},
  {t:'razones-proporciones',n:'prim-9',q:'En la proporcion a/b = c/d, el producto cruzado es:',c:'ad = bc',o:['ab = cd','ac = bd','ad = bc']},
  {t:'razones-proporciones',n:'prim-9',q:'Si 3:5 = 9:15, el medio proporcional es:',c:'5 y 9',o:['3 y 15','3 y 9','5 y 15']},
  {t:'razones-proporciones',n:'prim-9',q:'Para hacer 6 galletas se usan 2 huevos. Para 15 galletas:',c:'5 huevos',o:['3 huevos','4 huevos','6 huevos']},
  {t:'razones-proporciones',n:'prim-9',q:'Si 2:3 se escala por 4, la nueva razon es:',c:'8:12',o:['6:7','4:5','2:3']},
  {t:'razones-proporciones',n:'prim-9',q:'La razon 0.5:2 simplificada es:',c:'1:4',o:['1:2','2:1','5:20']},

  // === ESTADISTICA (20) ===
  {t:'estadistica',n:'7-11',q:'La media de 4,8,6,10 es:',c:'7',o:['6','8','28']},
  {t:'estadistica',n:'7-11',q:'La mediana de 3,7,8,12,15 es:',c:'8',o:['7','9','12']},
  {t:'estadistica',n:'7-11',q:'La mediana de 2,4,6,8 es:',c:'5',o:['4','6','6.5']},
  {t:'estadistica',n:'7-11',q:'La moda de 2,2,3,4,4,4,5 es:',c:'4',o:['2','3','5']},
  {t:'estadistica',n:'7-11',q:'El rango de 5,12,8,20,3 es:',c:'17',o:['15','20','12']},
  {t:'estadistica',n:'7-11',q:'La varianza de 2,4,6 es:',c:'8/3≈2.67',o:['2','4','6']},
  {t:'estadistica',n:'7-11',q:'La desviacion estandar es la raiz de:',c:'Varianza',o:['Media','Moda','Rango']},
  {t:'estadistica',n:'7-11',q:'La frecuencia absoluta de un dato es:',c:'Numero de veces que aparece',o:['El dato mismo','El porcentaje','La suma total']},
  {t:'estadistica',n:'7-11',q:'La frecuencia relativa se expresa en:',c:'Porcentaje',o:['Unidades','Decimal solamente','Numero entero']},
  {t:'estadistica',n:'7-11',q:'Un grafico de barras se usa para:',c:'Comparar categorias',o:['Mostrar tendencias','Ver distribucion continua','Comparar partes de un todo']},
  {t:'estadistica',n:'7-11',q:'Un histograma se usa para:',c:'Distribucion de datos continuos',o:['Comparar categorias','Ver proporcion','Mostrar relacion']},
  {t:'estadistica',n:'7-11',q:'Datos: 1,1,2,2,2,3,3,4. La media es:',c:'18/8=2.25',o:['2','3','2.5']},
  {t:'estadistica',n:'7-11',q:'Datos: 1,1,2,2,2,3,3,4. La mediana es:',c:'2',o:['2.5','3','2.25']},
  {t:'estadistica',n:'7-11',q:'Si todos los datos son iguales, la desviacion estandar es:',c:'0',o:['1','El mismo dato','No se puede calcular']},
  {t:'estadistica',n:'7-11',q:'El primer cuartil (Q1) deja el: (porcentaje de datos abajo)',c:'25%',o:['50%','75%','100%']},
  {t:'estadistica',n:'7-11',q:'Porcentaje de datos en el intervalo [x¯-σ, x¯+σ] en distribucion normal:',c:'68%',o:['95%','99%','50%']},
  {t:'estadistica',n:'7-11',q:'Datos: 6,7,8,9,10. La media es:',c:'8',o:['7','9','40']},
  {t:'estadistica',n:'7-11',q:'Datos: 6,7,8,9,10. La desviacion estandar es:',c:'√2≈1.41',o:['1','2','√3≈1.73']},
  {t:'estadistica',n:'7-11',q:'La frecuencia acumulada es:',c:'Suma de frecuencias hasta ese dato',o:['La frecuencia del dato','El ultimo dato','La frecuencia mayor']},
  {t:'estadistica',n:'7-11',q:'En un diagrama de caja, la "caja" abarca:',c:'Q1 a Q3',o:['Min a Max','Media ± σ','Q2 a Q4']},

  // === PROBABILIDAD (20) ===
  {t:'probabilidad',n:'8-11',q:'Al lanzar un dado, P(3) =',c:'1/6',o:['1/3','1/2','1']},
  {t:'probabilidad',n:'8-11',q:'Al lanzar un dado, P(par) =',c:'1/2',o:['1/6','1/3','2/3']},
  {t:'probabilidad',n:'8-11',q:'Al lanzar una moneda, P(cara) =',c:'1/2',o:['1','0','1/4']},
  {t:'probabilidad',n:'8-11',q:'La probabilidad de un evento seguro es:',c:'1',o:['0','0.5','Depende']},
  {t:'probabilidad',n:'8-11',q:'La probabilidad de un evento imposible es:',c:'0',o:['1','0.5','-1']},
  {t:'probabilidad',n:'8-11',q:'P(A ∪ B) = P(A) + P(B) - P(A ∩ B) se llama:',c:'Regla de la suma',o:['Regla del producto','Probabilidad condicional','Teorema de Bayes']},
  {t:'probabilidad',n:'8-11',q:'Dos eventos A y B son independientes si:',c:'P(A∩B)=P(A)P(B)',o:['P(A∪B)=P(A)+P(B)','P(A|B)=0','P(A∩B)=0']},
  {t:'probabilidad',n:'8-11',q:'Al lanzar 2 dados, P(suma 7) =',c:'6/36=1/6',o:['5/36','7/36','8/36=2/9']},
  {t:'probabilidad',n:'8-11',q:'Al lanzar 2 dados, P(suma 2) =',c:'1/36',o:['2/36=1/18','1/6','1/12']},
  {t:'probabilidad',n:'8-11',q:'En una bolsa con 3 rojas y 5 azules, P(roja)=',c:'3/8',o:['5/8','3/5','1/3']},
  {t:'probabilidad',n:'8-11',q:'P(A^c) = 1 - P(A) se llama:',c:'Regla del complemento',o:['Regla de la suma','Regla del producto','Ley de Morgan']},
  {t:'probabilidad',n:'8-11',q:'Al lanzar un dado, P(primo) = (primos: 2,3,5)',c:'1/2',o:['2/3','1/3','1/6']},
  {t:'probabilidad',n:'8-11',q:'P(A|B) se lee:',c:'Probabilidad de A dado B',o:['Probabilidad de A o B','Probabilidad de A y B','Probabilidad de A sin B']},
  {t:'probabilidad',n:'8-11',q:'Extraer una carta de un mazo (52 cartas), P(as)=',c:'4/52=1/13',o:['1/52','13/52=1/4','2/13']},
  {t:'probabilidad',n:'8-11',q:'Extraer una carta de un mazo, P(corazon)=',c:'13/52=1/4',o:['1/13','1/2','4/13']},
  {t:'probabilidad',n:'8-11',q:'Si P(A)=0.3, P(B)=0.5, P(A∩B)=0.15, son:',c:'Independientes',o:['Dependientes','Mut. excluyentes','Complementarios']},
  {t:'probabilidad',n:'8-11',q:'Si P(A∩B)=0, los eventos son:',c:'Mut. excluyentes',o:['Independientes','Dependientes','Complementarios']},
  {t:'probabilidad',n:'8-11',q:'El rango de una probabilidad es:',c:'[0,1]',o:('[0,∞)','(-∞,∞)','[0,100]')},
  {t:'probabilidad',n:'8-11',q:'(0.25)(0.25) =',c:'0.0625',o:['0.5','0.0625','0.625']},
  {t:'probabilidad',n:'8-11',q:'La probabilidad de lluvia es 0.7. P(no lluvia)=',c:'0.3',o:['0.7','0','1']},

  // === LOGICA (20) ===
  {t:'logica',n:'7-10',q:'p ∧ V es logicamente equivalente a:',c:'p',o:['V','F','-p']},
  {t:'logica',n:'7-10',q:'p ∨ F es logicamente equivalente a:',c:'p',o:['V','F','-p']},
  {t:'logica',n:'7-10',q:'La negacion de p es:',c:'-p',o:['p','V','F']},
  {t:'logica',n:'7-10',q:'p ∧ -p es:',c:'Falso',o:['Verdadero','p','-p']},
  {t:'logica',n:'7-10',q:'p ∨ -p es:',c:'Verdadero',o:['Falso','p','-p']},
  {t:'logica',n:'7-10',q:'-(p ∧ q) es equivalente a:',c:'-p ∨ -q',o:['-p ∧ -q','-(p ∨ q)','-p → -q']},
  {t:'logica',n:'7-10',q:'-(p ∨ q) es equivalente a:',c:'-p ∧ -q',o:['-p ∨ -q','-(p ∧ q)','-p → q']},
  {t:'logica',n:'7-10',q:'p → q es equivalente a:',c:'-p ∨ q',o:['p ∨ -q','-q → -p','q → p']},
  {t:'logica',n:'7-10',q:'La contrapositiva de p → q es:',c:'-q → -p',o:['q → p','-p → -q','p → -q']},
  {t:'logica',n:'7-10',q:'p ↔ q es verdadero cuando:',c:'p y q tienen el mismo valor',o:['p es verdadero','q es verdadero','p y q son falsos']},
  {t:'logica',n:'7-10',q:'Una proposicion es:',c:'Una oracion con valor de verdad',o:['Una pregunta','Un mandato','Una exclamacion']},
  {t:'logica',n:'7-10',q:'Si p=V, q=F, entonces p∧q es:',c:'Falso',o:['Verdadero','No se sabe','Depende']},
  {t:'logica',n:'7-10',q:'Si p=V, q=F, entonces p∨q es:',c:'Verdadero',o:['Falso','No se sabe','Depende']},
  {t:'logica',n:'7-10',q:'p ⊕ q (XOR) es verdadero cuando:',c:'p y q son diferentes',o:['p y q son iguales','p es verdadero','q es verdadero']},
  {t:'logica',n:'7-10',q:'El cuantificador universal ∀ significa:',c:'Para todo',o:['Existe','No existe','Para alguno']},
  {t:'logica',n:'7-10',q:'El cuantificador existencial ∃ significa:',c:'Existe al menos uno',o:['Para todo','No existe','Unico']},
  {t:'logica',n:'7-10',q:'∀x(P(x)) es falso si:',c:'Hay un x donde P(x) es falso',o:['Todos los x cumplen','Ningun x cumple','No hay x']},
  {t:'logica',n:'7-10',q:'En la tabla de verdad de p→q, cuando p=V y q=V:',c:'V',o:['F','No se sabe','Depende']},
  {t:'logica',n:'7-10',q:'En la tabla de verdad de p→q, cuando p=V y q=F:',c:'F',o:['V','No se sabe','Depende']},
  {t:'logica',n:'7-10',q:'La doble negacion --p es equivalente a:',c:'p',o:['-p','V','F']},

  // === MATRICES (20) ===
  {t:'matrices',n:'10-11',q:'Se suma matrices del mismo:',c:'Orden',o:['Valor','Determinante','Color']},
  {t:'matrices',n:'10-11',q:'[1,2|3,4] + [5,6|7,8] =',c:'[6,8|10,12]',o:['[5,12|21,32]','[1,2|3,4]','[5,6|7,8]']},
  {t:'matrices',n:'10-11',q:'2 * [1,3|2,4] =',c:'[2,6|4,8]',o:('[2,4|6,8]','[1,6|2,8]','[3,5|4,6]')},
  {t:'matrices',n:'10-11',q:'[1,2|3,4] * [1,0|0,1] =',c:'[1,2|3,4]',o:('[2,4|6,8]','[1,0|0,1]','[2,0|0,4]')},
  {t:'matrices',n:'10-11',q:'La matriz identidad 2x2 es:',c:'[1,0|0,1]',o:('[0,1|1,0]','[1,1|1,1]','[0,0|0,0]')},
  {t:'matrices',n:'10-11',q:'det([a,b|c,d]) =',c:'ad - bc',o:['ab - cd','ac - bd','ad + bc']},
  {t:'matrices',n:'10-11',q:'det([1,0|0,1]) =',c:'1',o:['0','-1','2']},
  {t:'matrices',n:'10-11',q:'det([2,0|0,3]) =',c:'6',o:['5','0','1']},
  {t:'matrices',n:'10-11',q:'La transpuesta de [1,2|3,4] es:',c:'[1,3|2,4]',o:('[4,3|2,1]','[1,2|3,4]','[2,1|4,3]')},
  {t:'matrices',n:'10-11',q:'Matriz con det=0 se llama:',c:'Singular',o:['Regular','Identidad','Diagonal']},
  {t:'matrices',n:'10-11',q:'A*I =',c:'A',o:['I','0','2A']},
  {t:'matrices',n:'10-11',q:'El producto de matrices es asociativo: A(BC) =',c:'(AB)C',o:['A(BC)','(AC)B','(AB)*C']},
  {t:'matrices',n:'10-11',q:'El producto de matrices NO es:',c:'Conmutativo',o:['Asociativo','Distributivo','Ninguna']},
  {t:'matrices',n:'10-11',q:'Una matriz 3x2 tiene:',c:'3 filas, 2 columnas',o:['2 filas, 3 columnas','3 filas, 3 columnas','2 filas, 2 columnas']},
  {t:'matrices',n:'10-11',q:'Para multiplicar AB, el numero de columnas de A debe ser:',c:'igual al numero de filas de B',o:['igual al de B','diferente','mayor que B']},
  {t:'matrices',n:'10-11',q:'det([3,1|2,4]) =',c:'10',o:['11','12','14']},
  {t:'matrices',n:'10-11',q:'La inversa de [1,0|0,1] es:',c:'[1,0|0,1]',o:('[0,1|1,0]','[-1,0|0,-1]','No existe')},
  {t:'matrices',n:'10-11',q:'Matriz cuadrada tiene:',c:'Igual numero de filas y columnas',o:['Mas filas','Mas columnas','Determinante 0']},
  {t:'matrices',n:'10-11',q:'det([1,2|2,4]) =',c:'0',o:['1','-3','8']},
  {t:'matrices',n:'10-11',q:'Suma de matrices es:',c:'Conmutativa',o:['No conmutativa','Solo para 2x2','Solo para identidad']},

  // === VECTORES (20) ===
  {t:'vectores',n:'10-11',q:'La magnitud de (3,4) es:',c:'5',o:['3','4','7']},
  {t:'vectores',n:'10-11',q:'La magnitud de (1,2,2) es:',c:'3',o:['2','5','√5≈2.24']},
  {t:'vectores',n:'10-11',q:'(2,3) + (4,1) =',c:'(6,4)',o:('(8,3)','(6,4)','(2,2)')},
  {t:'vectores',n:'10-11',q:'3*(1,4) =',c:'(3,12)',o:('(4,7)','(3,12)','(1,12)')},
  {t:'vectores',n:'10-11',q:'(2,1) - (3,4) =',c:'(-1,-3)',o:('(5,5)','(-1,-3)','(6,4)')},
  {t:'vectores',n:'10-11',q:'Producto punto (2,3)·(4,1) =',c:'11',o:['8','12','10']},
  {t:'vectores',n:'10-11',q:'Producto punto (1,0,0)·(0,1,0) =',c:'0',o:['1','-1','2']},
  {t:'vectores',n:'10-11',q:'Vectores ortogonales tienen producto punto:',c:'0',o:['1','-1','maximo']},
  {t:'vectores',n:'10-11',q:'La magnitud de un vector se calcula con:',c:'√(x²+y²)',o:['x+y','√(x²-y²)','x²+y²']},
  {t:'vectores',n:'10-11',q:'Un vector unitario tiene magnitud:',c:'1',o:['0','2','Depende']},
  {t:'vectores',n:'10-11',q:'El vector unitario en direccion de (3,4) es:',c:'(3/5,4/5)',o:('(1,1)','(3/5,4/5)','(3,4)/2')},
  {t:'vectores',n:'10-11',q:'Dos vectores son paralelos si:',c:'Uno es multiplo escalar del otro',o:['Producto punto=0','Tienen igual magnitud','Misma direccion']},
  {t:'vectores',n:'10-11',q:'(1,2,3)·(1,2,3) =',c:'14',o:['6','9','1']},
  {t:'vectores',n:'10-11',q:'La proyeccion escalar de u sobre v mide:',c:'u·v/|v|',o:['|u|','|v|','u·v|v|']},
  {t:'vectores',n:'10-11',q:'Producto cruz da como resultado:',c:'Un vector',o:['Un escalar','Una matriz','Un numero']},
  {t:'vectores',n:'10-11',q:'El producto cruz de vectores paralelos es:',c:'0',o:['Maximo','1','Depende']},
  {t:'vectores',n:'10-11',q:'(1,0)×(0,1) (en 3D) tiene magnitud:',c:'1',o:['0','-1','2']},
  {t:'vectores',n:'10-11',q:'El angulo entre (1,0) y (0,1) es:',c:'90°',o:['0°','45°','180°']},
  {t:'vectores',n:'10-11',q:'cos(θ) = u·v / (|u||v|) se usa para:',c:'Angulo entre vectores',o:['Producto cruz','Magnitud','Direccion']},
  {t:'vectores',n:'10-11',q:'La notacion ⟨x,y⟩ representa:',c:'Un vector fila',o:['Un punto','Una matriz','Un conjunto']},

  // === SUCESIONES (20) ===
  {t:'sucesiones',n:'9-11',q:'El termino general de 2,4,6,8,... es:',c:'2n',o:['n+2','n²','2n+1']},
  {t:'sucesiones',n:'9-11',q:'El termino general de 1,4,9,16,... es:',c:'n²',o:['2n','n+3','2^n']},
  {t:'sucesiones',n:'9-11',q:'El termino general de 3,6,9,12,... es:',c:'3n',o:['n+2','n+3','3n+1']},
  {t:'sucesiones',n:'9-11',q:'El 5to termino de a_n = 3n+1 es:',c:'16',o:['15','14','17']},
  {t:'sucesiones',n:'9-11',q:'El 10mo termino de a_n = n² es:',c:'100',o:['20','100','1024']},
  {t:'sucesiones',n:'9-11',q:'Sucesion aritmetica: 5,8,11,14,... d=',c:'3',o:['2','5','4']},
  {t:'sucesiones',n:'9-11',q:'Sucesion geometrica: 2,6,18,54,... r=',c:'3',o:['2','4','6']},
  {t:'sucesiones',n:'9-11',q:'La suma 1+2+3+...+100 es:',c:'5050',o:['5000','5050','5500']},
  {t:'sucesiones',n:'9-11',q:'La suma de n terminos de PA: S_n =',c:'n(a1+an)/2',o:['n(a1+an)','a1+an','n*a1']},
  {t:'sucesiones',n:'9-11',q:'En PA: a_n = a1 + (n-1)d. a1=3,d=2, a_10=',c:'21',o:['20','23','19']},
  {t:'sucesiones',n:'9-11',q:'En PG: a_n = a1*r^(n-1). a1=1,r=2, a_8=',c:'128',o:['64','256','16']},
  {t:'sucesiones',n:'9-11',q:'La suma infinita de PG con |r|<1 es:',c:'a1/(1-r)',o:['a1*r','a1/(r-1)','∞']},
  {t:'sucesiones',n:'9-11',q:'La sucesion 1,1,2,3,5,8,... es:',c:'Fibonacci',o:['Aritmetica','Geometrica','Armonica']},
  {t:'sucesiones',n:'9-11',q:'En una PA, la diferencia entre terminos consecutivos es:',c:'Constante',o:['Variable','Multiplicativa','Creciente']},
  {t:'sucesiones',n:'9-11',q:'En una PG, la razon entre terminos consecutivos es:',c:'Constante',o:['Variable','Aditiva','Decreciente']},
  {t:'sucesiones',n:'9-11',q:'Suma de 1+3+5+...+19 (10 impares):',c:'100',o:['90','110','95']},
  {t:'sucesiones',n:'9-11',q:'La sucesion 1/2, 1/4, 1/8, 1/16,... es PG con r=',c:'1/2',o:['2','1/4','1/8']},
  {t:'sucesiones',n:'9-11',q:'Suma infinita de 1 + 1/2 + 1/4 + 1/8 + ... =',c:'2',o:['1','3','∞']},
  {t:'sucesiones',n:'9-11',q:'Termino general de 1,4,7,10,13,...:',c:'3n-2',o:['n+3','2n-1','3n+1']},
  {t:'sucesiones',n:'9-11',q:'Termino general de 1, -1, 1, -1, 1,...:',c:'(-1)^(n-1)',o:['(-1)^n','1','-1']},

  // === GEO-ANALITICA (20) ===
  {t:'geo-analitica',n:'9-11',q:'La pendiente entre (2,3) y (5,11) es:',c:'8/3',o:['3/8','4','1']},
  {t:'geo-analitica',n:'9-11',q:'La ecuacion de la recta con pendiente 2 que pasa por (1,3) es:',c:'y=2x+1',o:['y=2x+3','y=2x-1','y=x+2']},
  {t:'geo-analitica',n:'9-11',q:'La distancia entre (3,1) y (7,4) es:',c:'5',o:['4','3','7']},
  {t:'geo-analitica',n:'9-11',q:'Ecuacion de recta que pasa por (0,0) y (2,4):',c:'y=2x',o:['y=4x','y=x+2','y=2x+1']},
  {t:'geo-analitica',n:'9-11',q:'La pendiente de una recta horizontal es:',c:'0',o:['1','∞','-1']},
  {t:'geo-analitica',n:'9-11',q:'Dos rectas con pendientes 2 y -1/2 son:',c:'Perpendiculares',o:['Paralelas','Oblicuas','Coincidentes']},
  {t:'geo-analitica',n:'9-11',q:'Las rectas y=3x+1 y y=3x-2 son:',c:'Paralelas',o:['Perpendiculares','Secantes','Coincidentes']},
  {t:'geo-analitica',n:'9-11',q:'Punto medio de (2,3) y (8,7):',c:'(5,5)',o:('(4,4)','(5,5)','(6,5)')},
  {t:'geo-analitica',n:'9-11',q:'Ecuacion de circunferencia centro (0,0) radio 3:',c:'x²+y²=9',o:['x²+y²=3','x²+y²=6','x+y=3']},
  {t:'geo-analitica',n:'9-11',q:'Ecuacion de circunferencia centro (1,2) radio 4:',c:'(x-1)²+(y-2)²=16',o:['(x+1)²+(y+2)²=16','x²+y²=16','(x-1)²+(y-2)²=4']},
  {t:'geo-analitica',n:'9-11',q:'La circunferencia x²+y²=25 tiene radio:',c:'5',o:['25','12.5','√5']},
  {t:'geo-analitica',n:'9-11',q:'La pendiente de una recta vertical  es:',c:'Indefinida',o:['0','1','∞']},
  {t:'geo-analitica',n:'9-11',q:'Ecuacion de la recta con pendiente -1 e intercepto 3:',c:'y=-x+3',o:['y=x+3','y=-x-3','y=x-3']},
  {t:'geo-analitica',n:'9-11',q:'El punto (2,3) satisface y > 2x?',c:'No, 3 < 4',o:['Si, 3 > 4','Si, igual','No, 3=4']},
  {t:'geo-analitica',n:'9-11',q:'Distancia de (0,0) a la recta y=3x+1:',c:'1/√10',o:['0','1','√10']},
  {t:'geo-analitica',n:'9-11',q:'La recta que pasa por (2,5) y (2,1) es:',c:'Vertical x=2',o:['Horizontal y=5','y=2x+1','x=5']},
  {t:'geo-analitica',n:'9-11',q:'El centro de x²+y²-6x+8y=0 es:',c:'(3,-4)',o:('(-3,4)','(6,-8)','(3,4)')},
  {t:'geo-analitica',n:'9-11',q:'Forma pendiente-intercepto de la recta:',c:'y=mx+b',o:['ax+by=c','y-y1=m(x-x1)','x/a+y/b=1']},
  {t:'geo-analitica',n:'9-11',q:'Dos puntos determinan:',c:'Una unica recta',o:['Dos rectas','Ninguna recta','Infinitas rectas']},
  {t:'geo-analitica',n:'9-11',q:'La pendiente de 2x+3y=6 es:',c:'-2/3',o:['2/3','-3/2','2']},
];

(async()=>{
  let ins=0,skp=0;
  for(let i=0;i<temas.length;i++){
    const e=temas[i];const src=S+'|'+e.t+'|'+i;const res=mkOpts(e.c,e.o);
    if((await p.query('SELECT id FROM exercises WHERE source=$1',[src])).rows.length>0){skp++;continue;}
    await p.query("INSERT INTO exercises(topic_id,question,latex_content,options,solution_steps,theory,difficulty,category,exam_year,source,archivo_origen,imagen,nivel)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)",
      [e.t,e.q,'',JSON.stringify(res.o),JSON.stringify([{math:e.q,expl:''}]),null,'facil','mep',2025,src,A,null,e.n||'7-11']);ins++;
  }
  console.log('Inserted:',ins,', Skipped:',skp);
  const r=await p.query('SELECT COUNT(1)cnt FROM exercises');
  console.log('TOTAL DB:',r.rows[0].cnt);
  await p.end();
})();
