const { Pool } = require('pg');

const pool = new Pool({
  user: 'postgres',
  host: 'localhost',
  database: 'mathmaty',
  password: 'Calg.1984',
  port: 5432,
});

const category = 'tec_paa';
const year = 2021;

const exercises = [
  // ===================================================================
  // SECTION 1: FOLLETO GUÍA 2021 - MATEMÁTICA/LOGIC (Items 1-16)
  // ===================================================================
  {
    topic: 'tec-logica',
    question: 'Premisa 1: Ningún auténtico deportista es perezoso. Premisa 2: Algunos practicantes de ejercicios son perezosos. De las premisas anteriores se sigue que',
    latex: '',
    options: ['Todo perezoso es auténtico deportista', 'Todos los practicantes de ejercicios son perezosos', 'Todos los practicantes de ejercicios son auténticos deportistas', 'Algunos practicantes de ejercicio no son auténticos deportistas'],
    steps: [
      { math: '\\text{Auténticos deportistas} \\cap \\text{Perezosos} = \\varnothing', expl: 'La premisa 1 indica que ser auténtico deportista y ser perezoso son mutuamente excluyentes.' },
      { math: '\\text{Algunos practicantes} \\in \\text{Perezosos}', expl: 'La premisa 2 indica que hay practicantes de ejercicio que son perezosos.' },
      { math: '\\text{Algunos practicantes} \\notin \\text{Aut. deportistas}', expl: 'Como esos practicantes perezosos no pueden ser auténticos deportistas, se concluye que algunos practicantes no son auténticos deportistas.' },
    ],
    theory: 'Conceptos: silogismo, conjuntos disjuntos, conclusión necesaria. Biblioteca sugerida: TEC/PAA Lógica.',
    source: 'folleto_guia_2021_final.pdf | p. 18 | ítem 1',
    year: 2021,
  },
  {
    topic: 'tec-logica',
    question: 'Ramiro y Digna tienen una familia de 3 hijos e hijas. Daniela es hija de Yalile. Alfredo es primo de Daniela. Elberth es hijo de Gener. Gener y Guiselle son hermanos. Daniela es nieta de Digna. Gener es tío de Daniela. Con certeza, ¿cuál de las opciones es correcta?',
    latex: '',
    options: ['Alfredo es hijo de Guiselle', 'Elberth es primo de Daniela', 'Alfredo y Elberth son primos', 'Alfredo y Elberth son hermanos'],
    steps: [
      { math: '\\text{Daniela} \\Rightarrow \\text{hija de Yalile}', expl: 'Daniela es hija de Yalile.' },
      { math: '\\text{Gener tío de Daniela} \\Rightarrow \\text{Gener hermano de Yalile}', expl: 'Gener es hermano de Yalile (padre/madre de Daniela).' },
      { math: '\\text{Gener y Guiselle son hermanos}', expl: 'Guiselle también es hermano/a de Gener y Yalile.' },
      { math: '\\text{Elberth hijo de Gener} \\Rightarrow \\text{primo de Daniela}', expl: 'Elberth es hijo de Gener, quien es tío de Daniela; por tanto, Elberth es primo de Daniela.' },
    ],
    theory: 'Conceptos: árbol genealógico, relaciones familiares, deducción. Biblioteca sugerida: TEC/PAA Lógica.',
    source: 'folleto_guia_2021_final.pdf | p. 18 | ítem 2',
    year: 2021,
  },
  {
    topic: 'tec-logica',
    question: 'Premisa 1: Ningún filósofo es abogado. Premisa 2: Todos los notarios son abogados. De las premisas anteriores se sigue que',
    latex: '',
    options: ['Ningún filósofo es notario', 'Algunos filósofos son notarios', 'Algunos abogados son filósofos', 'Todos los abogados son notarios'],
    steps: [
      { math: '\\text{Filósofos} \\cap \\text{Abogados} = \\varnothing', expl: 'Ningún filósofo es abogado.' },
      { math: '\\text{Notarios} \\subset \\text{Abogados}', expl: 'Todos los notarios son abogados.' },
      { math: '\\text{Filósofos} \\cap \\text{Notarios} = \\varnothing', expl: 'Si todos los notarios son abogados y ningún filósofo es abogado, entonces ningún filósofo puede ser notario.' },
    ],
    theory: 'Conceptos: silogismo, conjuntos disjuntos, transitividad. Biblioteca sugerida: TEC/PAA Lógica.',
    source: 'folleto_guia_2021_final.pdf | p. 18 | ítem 3',
    year: 2021,
  },
  {
    topic: 'tec-logica',
    question: 'Hay tres personas: Jorge, Lorena y Arturo que viven en provincias distintas: San José, Alajuela y Puntarenas, y tienen apellidos distintos: Berrocal, Castro y Soto. Se sabe que: Jorge no vive en San José ni Lorena en Alajuela. El que vive en Puntarenas es de apellido Soto. El que vive en San José no es de apellido Berrocal. Lorena no es de apellido Berrocal ni Castro. Con certeza, ¿dónde vive Arturo y cuál es su apellido?',
    latex: '',
    options: ['Alajuela - Castro', 'San José - Castro', 'Puntarenas - Soto', 'Alajuela - Berrocal'],
    steps: [
      { math: '\\text{Lorena no Berrocal ni Castro} \\Rightarrow \\text{Lorena Soto}', expl: 'Por eliminación, Lorena es de apellido Soto.' },
      { math: '\\text{Lorena Soto, Soto vive en Puntarenas} \\Rightarrow \\text{Lorena en Puntarenas}', expl: 'Quien vive en Puntarenas es Soto, y Lorena es Soto.' },
      { math: '\\text{Jorge no en San José, Lorena en Puntarenas} \\Rightarrow \\text{Jorge en Alajuela}', expl: 'La única provincia restante para Jorge es Alajuela.' },
      { math: '\\text{San José no Berrocal, no Soto, no lo es Lorena} \\Rightarrow \\text{San José Castro}', expl: 'En San José no puede vivir Berrocal ni Soto (Lorena), entonces es Castro.' },
      { math: '\\text{Arturo: San José - Castro}', expl: 'Arturo vive en San José y es de apellido Castro.' },
    ],
    theory: 'Conceptos: tabla de deducción, eliminación, certeza. Biblioteca sugerida: TEC/PAA Lógica.',
    source: 'folleto_guia_2021_final.pdf | pp. 18-19 | ítem 4',
    year: 2021,
  },
  {
    topic: 'tec-matematica',
    question: 'Considere la siguiente secuencia: 4/1, 9/4, 14/9, x, y, p. ¿Cuál es el valor de p?',
    latex: '\\frac{4}{1}, \\frac{9}{4}, \\frac{14}{9}, x, y, p',
    options: ['31/36', '24/25', '34/49', '29/36'],
    steps: [
      { math: '\\text{Numerador: }4,9,14,\\ldots', expl: 'El numerador aumenta en 5 cada vez: 4, 9, 14, 19, 24, 29.' },
      { math: '\\text{Denominador: }1,4,9,\\ldots', expl: 'El denominador son cuadrados perfectos: 1², 2², 3², 4², 5², 6².' },
      { math: 'x=\\frac{19}{16},\\ y=\\frac{24}{25},\\ p=\\frac{29}{36}', expl: 'El sexto término (p) tiene numerador 29 y denominador 36.' },
    ],
    theory: 'Conceptos: secuencias numéricas, patrones independientes en numerador y denominador. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'folleto_guia_2021_final.pdf | p. 19 | ítem 5',
    year: 2021,
  },
  {
    topic: 'tec-matematica',
    question: 'Considere la siguiente secuencia: 4, A, 7, C, 12, E, 21, G, ... ¿Cuáles son los dos elementos que continúan la secuencia?',
    latex: '4, A, 7, C, 12, E, 21, G, \\ldots',
    options: ['32, I', '38, I', '32, H', '36, H'],
    steps: [
      { math: '\\text{Posiciones impares: }4,7,12,21,\\ldots', expl: 'Las diferencias son: 3, 5, 9, ... que se duplican cada vez.' },
      { math: '21+11=32', expl: 'La siguiente diferencia es 11 (9+2), dando 32.' },
      { math: '\\text{Posiciones pares: }A(1),C(3),E(5),G(7),\\ldots', expl: 'Son letras vocales/consonantes alternadas: A=1, C=3, E=5, G=7.' },
      { math: '\\text{Siguiente letra: }I=9', expl: 'La letra que continúa es I (novena letra del alfabeto).' },
    ],
    theory: 'Conceptos: secuencias combinadas (numérica y alfabética), diferencias sucesivas. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'folleto_guia_2021_final.pdf | p. 19 | ítem 10',
    year: 2021,
  },
  {
    topic: 'tec-logica',
    question: 'Premisa 2: Si como un postre, entonces no saldré en la noche. Premisa 3: Si no salgo en la noche, entonces veré una película. Conclusión: Si me ejercito, entonces veré una película. Para que se deduzca la conclusión, ¿cuál debe ser la premisa 1?',
    latex: '',
    options: ['Si me ejercito, entonces comeré un postre', 'Si veo una película, entonces me ejercitaré', 'Si me ejercito, entonces no saldré en la noche', 'Si veo una película, entonces comeré un postre'],
    steps: [
      { math: 'P_2: \\text{Postre} \\Rightarrow \\neg\\text{Salir}', expl: 'La premisa 2 relaciona postre con no salir.' },
      { math: 'P_3: \\neg\\text{Salir} \\Rightarrow \\text{Película}', expl: 'La premisa 3 relaciona no salir con ver película.' },
      { math: '\\text{Postre} \\Rightarrow \\text{Película}', expl: 'Encadenando P2 y P3 se obtiene esta relación.' },
      { math: '\\text{Ejercicio} \\Rightarrow \\text{Postre} \\Rightarrow \\text{Película}', expl: 'Para obtener "Ejercicio ⇒ Película", la premisa faltante debe ser "Ejercicio ⇒ Postre".' },
    ],
    theory: 'Conceptos: condicional, transitividad lógica, encadenamiento. Biblioteca sugerida: TEC/PAA Lógica.',
    source: 'folleto_guia_2021_final.pdf | p. 20 | ítem 11',
    year: 2021,
  },
  {
    topic: 'tec-matematica',
    question: 'Considere la secuencia: 5/(n⁵ + 1), 7/(n⁶ + 2), 9/(n⁷ + 3)... ¿Cuál es el quinto término de la secuencia?',
    latex: '\\frac{5}{n^5+1}, \\frac{7}{n^6+2}, \\frac{9}{n^7+3}, \\ldots',
    options: ['11/(n⁸ + 4)', '13/(n⁹ + 5)', '11/(n⁹ + 5)', '13/(n⁸ + 4)'],
    steps: [
      { math: '\\text{Numerador: }5,7,9,\\ldots', expl: 'Aumenta de 2 en 2: 5,7,9,11,13.' },
      { math: '\\text{Exponente: }5,6,7,\\ldots', expl: 'Aumenta de 1 en 1: 5,6,7,8,9.' },
      { math: '\\text{Sumando: }1,2,3,\\ldots', expl: 'Aumenta de 1 en 1: 1,2,3,4,5.' },
      { math: '\\text{5to término: }\\frac{13}{n^9+5}', expl: 'Numerador 13, exponente 9, sumando 5.' },
    ],
    theory: 'Conceptos: secuencias con patrones independientes. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'folleto_guia_2021_final.pdf | p. 20 | ítem 12',
    year: 2021,
  },
  {
    topic: 'tec-matematica',
    question: '¿Cuál es el valor de z en la secuencia: 1, 4, 2, 8, 6, w, x, y, z?',
    latex: '1, 4, 2, 8, 6, w, x, y, z',
    options: ['22', '24', '86', '88'],
    steps: [
      { math: '1\\times4=4', expl: 'Primer término por 4 da el segundo.' },
      { math: '4-2=2', expl: 'Segundo menos 2 da el tercero.' },
      { math: '2\\times4=8,\\ 8-2=6', expl: 'El patrón es: multiplicar por 4, luego restar 2, alternadamente.' },
      { math: '6\\times4=24,\\ 24-2=22,\\ 22\\times4=88', expl: 'Continuando: w=24, x=22, y=88, y-2=z, entonces z=86.' },
      { math: 'z=86', expl: 'Siguiendo el patrón: 88-2=86.' },
    ],
    theory: 'Conceptos: patrones alternados, multiplicación y resta. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'folleto_guia_2021_final.pdf | p. 20 | ítem 13',
    year: 2021,
  },
  {
    topic: 'tec-logica',
    question: 'Premisa 1: Todo C es S. Premisa 2: Algunos C no son G. Premisa 3: Algunos F no son C. Premisa 4: Algunos G no son S. Premisa 5: Todo E no es S. Premisa 6: C no es igual a S. De las premisas anteriores se sigue que',
    latex: '',
    options: ['Todo G no es S', 'Todo S no es F', 'Algunos C son E', 'Algunos S no son C'],
    steps: [
      { math: 'C \\subset S', expl: 'La premisa 1 indica que todo C está dentro de S.' },
      { math: 'C \\neq S', expl: 'La premisa 6 dice que C es un subconjunto propio de S.' },
      { math: '\\text{Existen elementos de }S\\text{ que no son }C', expl: 'Como C es subconjunto propio de S, hay al menos un elemento de S que no es C.' },
      { math: '\\text{Algunos S no son C}', expl: 'Esta es la única conclusión que se sigue con certeza.' },
    ],
    theory: 'Conceptos: subconjuntos propios, cuantificadores, conclusión necesaria. Biblioteca sugerida: TEC/PAA Lógica.',
    source: 'folleto_guia_2021_final.pdf | p. 20 | ítem 14',
    year: 2021,
  },
  {
    topic: 'tec-logica',
    question: 'Cinco personas, al ser interrogadas sobre quién se comió el último pedazo de pastel, manifestaron lo siguiente: B: "Fue E." A: "Fue B." E: "B miente." M: "Yo no fui." K: "Fui yo." Si sabe que solo una de ellas dice la verdad, ¿quién se comió el último pedazo de pastel?',
    latex: '',
    options: ['A', 'B', 'E', 'M'],
    steps: [
      { math: '\\text{B dice: Fue E. A dice: Fue B.}', expl: 'Analizamos cada posible culpable.' },
      { math: '\\text{Si fue E: B dice verdad, E miente, A miente, M verdad, K miente}', expl: 'Dos verdades (B y M) → no puede ser.' },
      { math: '\\text{Si fue M: todos mienten excepto...}', expl: 'Probando M: B miente (no fue E), A miente (no fue B), E dice verdad (B miente), M miente (fue M), K miente (no fue K). Solo E verdad → funciona.' },
      { math: '\\text{Fue M}', expl: 'Con M como culpable, solo E dice la verdad.' },
    ],
    theory: 'Conceptos: verdad/mentira, análisis de casos, lógica proposicional. Biblioteca sugerida: TEC/PAA Lógica.',
    source: 'folleto_guia_2021_final.pdf | pp. 20-21 | ítem 15',
    year: 2021,
  },
  {
    topic: 'tec-logica',
    question: 'Suponga que para cinco objetos V, W, X, Y y Z se sabe que: V es el doble de W y a lo sumo tiene el tamaño de Y. El tamaño de X junto con el de Z representan el tamaño de W. Considere las afirmaciones: A. Y mide el doble de W. B. Y mide más que el doble de X. C. Z mide al menos la mitad de W. De las afirmaciones anteriores, ¿cuáles se cumplen con certeza?',
    latex: '',
    options: ['A y B', 'A y C', 'B y C', 'Solo B'],
    steps: [
      { math: 'V = 2W,\\ V \\leq Y', expl: 'V es el doble de W y V es menor o igual que Y.' },
      { math: 'X + Z = W', expl: 'X y Z suman el tamaño de W.' },
      { math: 'Y \\geq 2W,\\ Y > 2X', expl: 'Y es al menos 2W. Como X < W, entonces Y > 2X. Afirmación B es cierta.' },
      { math: 'Z = W - X,\\ X > 0 \\Rightarrow Z < W', expl: 'Z podría ser menor que la mitad de W si X > W/2. C no es necesariamente cierta.' },
      { math: '\\text{Solo B}', expl: 'Solo la afirmación B se cumple con certeza.' },
    ],
    theory: 'Conceptos: relaciones de tamaño, desigualdades, certeza. Biblioteca sugerida: TEC/PAA Lógica.',
    source: 'folleto_guia_2021_final.pdf | p. 21 | ítem 16',
    year: 2021,
  },
  {
    topic: 'tec-matematica',
    question: 'Considere la secuencia: 3, 1, -1, -3. Si n representa la posición de cada término, ¿cuál es la fórmula que genera los términos de esta secuencia?',
    latex: '3, 1, -1, -3',
    options: ['n - 2', '4 - n', '5 - 2n', '2n - 5'],
    steps: [
      { math: 'n=1 \\Rightarrow 3,\\ n=2 \\Rightarrow 1,\\ n=3 \\Rightarrow -1,\\ n=4 \\Rightarrow -3', expl: 'Verificamos cada fórmula con los términos dados.' },
      { math: '5-2(1)=3,\\ 5-2(2)=1,\\ 5-2(3)=-1,\\ 5-2(4)=-3', expl: 'La fórmula 5-2n cumple para todos los términos.' },
      { math: '\\text{Fórmula: }5-2n', expl: 'La expresión que genera la secuencia es 5 - 2n.' },
    ],
    theory: 'Conceptos: secuencia aritmética, término general, fórmula explícita. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'folleto_guia_2021_final.pdf | p. 21 | ítem 17',
    year: 2021,
  },
  {
    topic: 'tec-matematica',
    question: 'Suponga que en la confección de un mapa de Costa Rica se utilizó una escala donde 0,75 cm equivale a 10 km. Si en ese mapa la distancia entre dos ciudades es de 6 cm, ¿cuál es la distancia real?',
    latex: '0.75\\text{ cm} = 10\\text{ km}',
    options: ['15 km', '45 km', '60 km', '80 km'],
    steps: [
      { math: '\\frac{0.75}{10} = \\frac{6}{x}', expl: 'Se plantea la proporción: escala = distancia en mapa / distancia real.' },
      { math: 'x = \\frac{6 \\times 10}{0.75}', expl: 'Se despeja x usando regla de tres directa.' },
      { math: 'x = \\frac{60}{0.75} = 80', expl: 'La distancia real es 80 km.' },
    ],
    theory: 'Conceptos: escala, proporción, regla de tres directa. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'folleto_guia_2021_final.pdf | p. 21 | ítem 18',
    year: 2021,
  },
  {
    topic: 'tec-matematica',
    question: 'Observe la información sobre esperanza de vida: España 84.1, Honduras 76.2, Irlanda 81.5, Jamaica 76.2, Marruecos 76.2, Portugal 81.5, Tanzania 63.9. Si m es el valor máximo, s el mínimo, r el más frecuente y p el promedio, ¿cuál opción presenta el orden correcto?',
    latex: '',
    options: ['s < p < r < m', 'm < p < r < s', 's < r < p < m', 'm < r < p < s'],
    steps: [
      { math: 'm = 84.1\\text{ (España)}', expl: 'El valor máximo es 84.1.' },
      { math: 's = 63.9\\text{ (Tanzania)}', expl: 'El valor mínimo es 63.9.' },
      { math: 'r = 76.2', expl: 'La moda (valor más frecuente) es 76.2 (Honduras, Jamaica, Marruecos).' },
      { math: 'p = \\frac{84.1+76.2+81.5+76.2+76.2+81.5+63.9}{7} = 77.1', expl: 'El promedio aproximado es 77.1.' },
      { math: '63.9 < 76.2 < 77.1 < 84.1 \\Rightarrow s < r < p < m', expl: 'Orden correcto: s < r < p < m.' },
    ],
    theory: 'Conceptos: estadística descriptiva, máximo, mínimo, moda, promedio. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'folleto_guia_2021_final.pdf | pp. 21-22 | ítem 19',
    year: 2021,
  },
  // ===================================================================
  // SECTION 2: FOLLETO GUÍA 2021 - MATEMÁTICA (Items 21-35)
  // ===================================================================
  {
    topic: 'tec-matematica',
    question: 'Sobre el conjunto H = {a, 3, 7, w, 20} se define la operación x ⊙ y = x + 2y. ¿Cuál es el resultado de a ⊙ (7 ⊙ w)?',
    latex: 'x \\odot y = x + 2y,\\ H = \\{a, 3, 7, w, 20\\}',
    options: ['a + 14 + 2w', 'a + 14 + 4w', 'x + 14 + 2y', 'x + 14 + 4w'],
    steps: [
      { math: '7 \\odot w = 7 + 2w', expl: 'Aplicamos la definición: x⊙y = x + 2y, con x=7, y=w.' },
      { math: 'a \\odot (7+2w) = a + 2(7+2w)', expl: 'Sustituimos el resultado en la operación exterior.' },
      { math: 'a + 14 + 4w', expl: 'Aplicamos propiedad distributiva: 2(7+2w) = 14 + 4w.' },
    ],
    theory: 'Conceptos: operación definida, evaluación de expresiones, álgebra. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'folleto_guia_2021_final.pdf | p. 22 | ítem 21',
    year: 2021,
  },
  {
    topic: 'tec-matematica',
    question: 'Considere la siguiente definición: "Un número primo p se llama primo de Germain si 2p + 1 es primo". ¿Cuál es un número primo de Germain?',
    latex: 'p\\text{ primo de Germain} \\iff 2p+1\\text{ es primo}',
    options: ['5', '7', '13', '17'],
    steps: [
      { math: '2(5)+1=11\\text{ (primo)}', expl: 'Para p=5, 2p+1=11 que es primo. 5 es primo de Germain.' },
      { math: '2(7)+1=15\\text{ (no primo)}', expl: 'Para p=7, 2p+1=15 que no es primo.' },
      { math: '2(13)+1=27\\text{ (no primo)}', expl: 'Para p=13, 2p+1=27 que no es primo.' },
      { math: '2(17)+1=35\\text{ (no primo)}', expl: 'Para p=17, 2p+1=35 que no es primo.' },
      { math: '\\text{Respuesta: }5', expl: '5 es el único primo de Germain entre las opciones.' },
    ],
    theory: 'Conceptos: números primos, definición, verificación. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'folleto_guia_2021_final.pdf | p. 22 | ítem 23',
    year: 2021,
  },
  {
    topic: 'tec-matematica',
    question: 'En un local comercial, por la compra de un artículo A que cuesta 50 000 colones, se le ofrece un descuento de 7% y, por la de un artículo B con valor de 30 000 colones, un 5%. Sin embargo, en una promoción, al comprar los dos artículos juntos, se ofrece un descuento de 10% sobre el monto total. ¿Cuál es la diferencia en colones entre el descuento al comprar los dos artículos juntos y de manera individual?',
    latex: '',
    options: ['1600', '3000', '5000', '8000'],
    steps: [
      { math: '\\text{Desc. individual: }0.07(50000)+0.05(30000)=3500+1500=5000', expl: 'Suma de descuentos individuales.' },
      { math: '\\text{Desc. conjunto: }0.10(50000+30000)=0.10(80000)=8000', expl: 'Descuento por comprar juntos.' },
      { math: '8000-5000=3000', expl: 'La diferencia es 3000 colones a favor de la compra conjunta.' },
    ],
    theory: 'Conceptos: porcentajes, descuentos, diferencia. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'folleto_guia_2021_final.pdf | p. 22 | ítem 24',
    year: 2021,
  },
  {
    topic: 'tec-logica',
    question: 'Hay 50 lápices de color en una caja: 20 son verdes, 10 son amarillos, 10 son rojos y entre los restantes, algunos son negros y otros azules. ¿Cuántos lápices se deben sacar de la caja como mínimo, sin mirarlos, para tener seguridad de que se obtuvo 10 lápices del mismo color?',
    latex: '',
    options: ['28', '36', '37', '38'],
    steps: [
      { math: '\\text{Verdes: }20,\\text{ Amarillos: }10,\\text{ Rojos: }10,\\text{ Negros+Azules: }10', expl: 'Distribución de colores.' },
      { math: '\\text{Peor caso: }9V+9Am+9R+10(N \\cup Az)', expl: 'Del grupo verde podemos sacar hasta 9 sin llegar a 10. Lo mismo para amarillos y rojos.' },
      { math: '9+9+9+10=37', expl: 'En el peor caso, sacamos 37 sin tener 10 del mismo color.' },
      { math: '37+1=38', expl: 'El siguiente lápiz completa 10 de algún color.' },
    ],
    theory: 'Conceptos: principio del palomar, caso peor, certeza. Biblioteca sugerida: TEC/PAA Lógica.',
    source: 'folleto_guia_2021_final.pdf | p. 22 | ítem 26',
    year: 2021,
  },
  {
    topic: 'tec-matematica',
    question: 'Sobre el conjunto A = {1, 2, 3, 4} se define la operación ⊕ por medio de la tabla: fila 1: 3,2,1,1; fila 2: 1,1,3,4; fila 3: 3,2,2,4; fila 4: 4,1,2,1. Por ejemplo, 2⊕3 = 3. ¿Cuál es el resultado de (4⊕2)⊕(2⊕3)?',
    latex: '',
    options: ['1', '2', '3', '4'],
    steps: [
      { math: '4 \\oplus 2 = 1', expl: 'Buscamos en la tabla: fila 4, columna 2 → 1.' },
      { math: '2 \\oplus 3 = 3', expl: 'Fila 2, columna 3 → 3 (dado en el ejemplo).' },
      { math: '1 \\oplus 3 = 3', expl: 'Fila 1, columna 3 → 1⊕3 = 1.' },
      { math: '\\text{Resultado: }1', expl: 'El resultado de la operación es 1.' },
    ],
    theory: 'Conceptos: operación definida por tabla, lectura de tabla, composición. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'folleto_guia_2021_final.pdf | pp. 22-23 | ítem 27',
    year: 2021,
  },
  {
    topic: 'tec-matematica',
    question: 'En una soda ofrecen almuerzos que consisten en una ensalada, un plato fuerte, un refresco y un postre. Cierto día tienen dos tipos de ensalada, tres de refresco y dos de postre. El cocinero sabe que si llegan 30 clientes podrá servirles un menú completo diferente a cada uno, pero si llegan 40 no podrá lograrlo. ¿Cuántas opciones de plato fuerte ofrece la soda?',
    latex: '',
    options: ['3', '4', '10', '23'],
    steps: [
      { math: '\\text{Total combinaciones} = 2 \\times p \\times 3 \\times 2 = 12p', expl: 'Donde p es el número de platos fuertes.' },
      { math: '30 \\leq 12p < 40', expl: 'Con 30 clientes hay suficientes combinaciones; con 40 no.' },
      { math: '12p \\geq 30 \\Rightarrow p \\geq 2.5', expl: 'p debe ser al menos 3.' },
      { math: '12p < 40 \\Rightarrow p < 3.33', expl: 'p debe ser menor que 3.33.' },
      { math: 'p = 3', expl: 'El único entero que cumple es p = 3.' },
    ],
    theory: 'Conceptos: principio multiplicativo, inecuaciones, conteo. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'folleto_guia_2021_final.pdf | p. 23 | ítem 28',
    year: 2021,
  },
  {
    topic: 'tec-matematica',
    question: 'Hay 3 turistas, 2 destinos diferentes para viajar y cada turista solo puede ir a un destino. ¿De cuántas maneras distintas se pueden organizar los viajes?',
    latex: '',
    options: ['4', '5', '6', '8'],
    steps: [
      { math: '\\text{Cada turista elige entre 2 destinos}', expl: 'Cada uno de los 3 turistas tiene 2 opciones.' },
      { math: '2 \\times 2 \\times 2 = 8', expl: 'Por el principio multiplicativo: 2³ = 8 formas.' },
    ],
    theory: 'Conceptos: principio multiplicativo, conteo con repetición. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'folleto_guia_2021_final.pdf | p. 23 | ítem 29',
    year: 2021,
  },
  {
    topic: 'tec-matematica',
    question: 'En una casa hay 6 personas celebrando un cumpleaños y van a repartir un pastel. El cumpleañero se come la mitad. Los demás hacen una fila para recibir su porción que corresponde a la mitad de lo que queda, excepto el último que se come lo restante. ¿Qué porción del pastel le correspondió al cuarto de la fila?',
    latex: '',
    options: ['1/4', '1/8', '1/16', '1/32'],
    steps: [
      { math: '\\text{Cumpleañero: }\\frac{1}{2},\\text{ Queda: }\\frac{1}{2}', expl: 'El primero (cumpleañero) se come la mitad.' },
      { math: '\\text{Fila 1: }\\frac{1}{2}\\times\\frac{1}{2}=\\frac{1}{4},\\text{ Queda: }\\frac{1}{4}', expl: 'El primero de la fila se come la mitad de lo que queda.' },
      { math: '\\text{Fila 2: }\\frac{1}{8},\\text{ Queda: }\\frac{1}{8}', expl: 'El segundo se come la mitad de lo que queda.' },
      { math: '\\text{Fila 3: }\\frac{1}{16},\\text{ Queda: }\\frac{1}{16}', expl: 'El tercero se come la mitad de lo que queda.' },
      { math: '\\text{Fila 4: }\\frac{1}{16}', expl: 'El cuarto (penúltimo) se come lo restante, que es 1/16.' },
    ],
    theory: 'Conceptos: fracciones, mitad de un resto, secuencia. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'folleto_guia_2021_final.pdf | p. 23 | ítem 30',
    year: 2021,
  },
  {
    topic: 'tec-matematica',
    question: 'Considere los números naturales de tres cifras n = abc. La fórmula que representa la suma de los dígitos de n es: S = a + b + c. Considere las proposiciones: A. Hay seis números tales que S = 3. B. S < 30. C. Hay más números que cumplen S = 27 que S = 26. De las anteriores, ¿cuáles son verdaderas?',
    latex: 'n=abc,\\ S=a+b+c',
    options: ['Solo B', 'A y B', 'B y C', 'A y C'],
    steps: [
      { math: '\\text{S=3: }a\\geq1,\\ a+b+c=3', expl: 'Combinaciones: (1,0,2),(1,1,1),(1,2,0),(2,0,1),(2,1,0),(3,0,0) → 6 números. A es verdadera.' },
      { math: '\\text{S < 30 siempre, pues máx S = 9+9+9 = 27}', expl: 'La suma máxima de tres dígitos es 27. B es verdadera.' },
      { math: '\\text{S=27: solo 999. S=26: 998,989,899 → 3 números}', expl: 'S=27 tiene 1 número, S=26 tiene 3. C es falsa.' },
      { math: '\\text{A y B son verdaderas}', expl: 'Solo A y B son proposiciones verdaderas.' },
    ],
    theory: 'Conceptos: combinatoria, suma de dígitos, conteo. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'folleto_guia_2021_final.pdf | p. 23 | ítem 31',
    year: 2021,
  },
  {
    topic: 'tec-matematica',
    question: '¿Cuántos números enteros k cumplen que 196 < k < 361?',
    latex: '196 < k < 361',
    options: ['163', '164', '165', '166'],
    steps: [
      { math: 'k \\in \\{197, 198, \\ldots, 360\\}', expl: 'Los enteros estrictamente entre 196 y 361.' },
      { math: '360 - 197 + 1 = 164', expl: 'Cantidad = último - primero + 1.' },
    ],
    theory: 'Conceptos: conteo de enteros en un intervalo, desigualdades. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'folleto_guia_2021_final.pdf | p. 23 | ítem 32',
    year: 2021,
  },
  {
    topic: 'tec-matematica',
    question: 'Sea N el mayor número entero con cifras diferentes, ninguna de ellas cero, y múltiplo de 24. ¿Cuál es la cifra que ocupa el lugar de las decenas de N?',
    latex: '',
    options: ['1', '2', '3', '4'],
    steps: [
      { math: '\\text{N múltiplo de 24 = múltiplo de 8 y de 3}', expl: '24 = 8 × 3.' },
      { math: '\\text{Máximo con 9 cifras distintas: }987654321', expl: 'El mayor número de 9 cifras distintas sin cero.' },
      { math: '\\text{Verificar divisibilidad entre 3 y 8}', expl: 'Suma dígitos = 45, divisible entre 3. Últimas 3 cifras deben ser divisibles entre 8.' },
      { math: '\\text{N = }987654312', expl: 'Ajustando las últimas cifras para que sea múltiplo de 8, la decena es 1.' },
    ],
    theory: 'Conceptos: divisibilidad, múltiplos, criterios de divisibilidad. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'folleto_guia_2021_final.pdf | pp. 23-24 | ítem 33',
    year: 2021,
  },
  {
    topic: 'tec-matematica',
    question: '¿Cuántos números enteros hay desde 32 hasta 74?',
    latex: '32 \\leq k \\leq 74',
    options: ['41', '42', '43', '44'],
    steps: [
      { math: '74 - 32 + 1 = 43', expl: 'Cantidad de enteros desde a hasta b inclusive: b - a + 1.' },
    ],
    theory: 'Conceptos: conteo de enteros en intervalo cerrado. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'folleto_guia_2021_final.pdf | p. 24 | ítem 34',
    year: 2021,
  },
  {
    topic: 'tec-matematica',
    question: 'En el conjunto de los números reales se define la operación ∆ como x∆y = x²·y. Considere las afirmaciones: A. –√2∆1 = 2. B. Para que a∆b = b, el único valor de a es 1. C. a∆b = b∆a solo se cumple si a = b. De las afirmaciones anteriores, ¿cuáles son verdaderas?',
    latex: 'x\\Delta y = x^2y',
    options: ['Solo A', 'Solo B', 'B y C', 'A y C'],
    steps: [
      { math: '(-\\sqrt{2})\\Delta 1 = (-\\sqrt{2})^2(1) = 2(1) = 2', expl: 'A es verdadera.' },
      { math: 'a\\Delta b = a^2b = b \\Rightarrow a^2b-b=0 \\Rightarrow b(a^2-1)=0', expl: 'Se cumple si a=1, a=-1 o b=0. No solo a=1. B es falsa.' },
      { math: 'a\\Delta b = b\\Delta a \\Rightarrow a^2b = b^2a \\Rightarrow a^2b - b^2a = 0 \\Rightarrow ab(a-b)=0', expl: 'Se cumple si a=0, b=0 o a=b. C es verdadera.' },
      { math: '\\text{A y C son verdaderas}', expl: 'Las afirmaciones verdaderas son A y C.' },
    ],
    theory: 'Conceptos: operación definida, álgebra, ecuaciones. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'folleto_guia_2021_final.pdf | p. 24 | ítem 35',
    year: 2021,
  },
  {
    topic: 'tec-matematica',
    question: 'Considere las figuras de polígonos regulares (triángulo equilátero, cuadrado, hexágono regular), donde todos tienen el mismo perímetro. Se puede garantizar con certeza que',
    latex: '',
    options: ['El cuadrado tiene mayor área que el triángulo', 'El triángulo tiene mayor área que el hexágono', 'El triángulo tiene mayor área que el cuadrado', 'El cuadrado tiene mayor área que el hexágono'],
    steps: [
      { math: 'P\\text{ igual para todos}', expl: 'Todos los polígonos tienen el mismo perímetro P.' },
      { math: 'A_\\triangle = \\frac{P^2}{12\\sqrt{3}},\\ A_\\square = \\frac{P^2}{16},\\ A_\\hexagon = \\frac{P^2\\sqrt{3}}{24}', expl: 'Áreas de polígonos regulares con perímetro P.' },
      { math: '\\frac{P^2}{16} > \\frac{P^2}{12\\sqrt{3}}', expl: 'El cuadrado tiene mayor área que el triángulo.' },
      { math: '\\text{Cuadrado > Triángulo}', expl: 'A igual perímetro, a más lados mayor área.' },
    ],
    theory: 'Conceptos: áreas de polígonos regulares, perímetro fijo, comparación. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'folleto_guia_2021_final.pdf | p. 24 | ítem 36',
    year: 2021,
  },
  // ===================================================================
  // SECTION 3: FOLLETO GUÍA 2021 - VERBAL (Items 51-80)
  // ===================================================================
  {
    topic: 'tec-verbal',
    question: 'Según el texto sobre Amelia Earhart: "La búsqueda de Amelia Earhart es un rompecabezas ______, y un desafío que Ballard disfruta. Así como también lo hacen los otros miembros de la tripulación, quienes no encuentran respuesta al ______ de cuánto podría haber sobrevivido Earhart en la isla." ¿Cuáles palabras completan el párrafo con sentido lógico?',
    latex: '',
    options: ['infinito - secreto', 'enredado - cálculo', 'inconcluso - enigma', 'legendario - desconcierto'],
    steps: [
      { math: '\\text{rompecabezas ____}', expl: 'Un rompecabezas inconcluso es aquel que no se ha terminado de resolver.' },
      { math: '\\text{no encuentran respuesta al ____}', expl: 'La falta de respuesta apunta a un enigma (misterio sin resolver).' },
      { math: '\\text{inconcluso - enigma}', expl: 'Ambas palabras mantienen coherencia con el contexto de búsqueda sin resolver.' },
    ],
    theory: 'Conceptos: coherencia textual, completar párrafo, campo semántico. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | p. 29 | ítem 51',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Según el texto: "Hay personas que se caracterizan por sus ______ y ______; mientras que hay otras que solo viven en la sensatez y realidad." ¿Qué palabras completan el enunciado con sentido lógico?',
    latex: '',
    options: ['locuras - excesos', 'objetivos - sueños', 'precauciones - torpezas', 'excentricidades - fantasías'],
    steps: [
      { math: '\\text{se contraponen a "sensatez y realidad"}', expl: 'Las palabras deben contrastar con sensatez y realidad.' },
      { math: '\\text{excentricidades y fantasías}', expl: 'Excentricidades (rareza) y fantasías (imaginación) se oponen a sensatez y realidad.' },
      { math: '\\text{excentricidades - fantasías}', expl: 'Es la única opción que presenta el contraste adecuado.' },
    ],
    theory: 'Conceptos: antonimia contextual, contraste semántico, coherencia. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | p. 29 | ítem 52',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Según el texto: "Mariela, al percatarse de que ya era tarde, salió de su casa y ______, ______, pues no podía perder la cita médica que tenía programada." ¿Cuáles palabras completan el párrafo con sentido lógico?',
    latex: '',
    options: ['enérgica - nerviosa', 'rauda - preocupada', 'precipitada - pesimista', 'aturdida - decepcionada'],
    steps: [
      { math: '\\text{ya era tarde, no podía perder la cita}', expl: 'La urgencia de llegar a tiempo es la clave.' },
      { math: '\\text{rauda (rápida) y preocupada}', expl: 'Rauda indica prisa y preocupada refleja su estado de ánimo.' },
      { math: '\\text{rauda - preocupada}', expl: 'Ambas palabras son coherentes con la situación descrita.' },
    ],
    theory: 'Conceptos: coherencia textual, adverbios de modo, contexto. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | p. 29 | ítem 54',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Según el texto: "Hoy, la definición de ______, se ha ensanchado desde la noción tradicional de saber leer y escribir hasta incluir la ______ de aprender, comprender e interactuar con la tecnología de manera significativa." ¿Cuáles palabras completan el párrafo con sentido lógico?',
    latex: '',
    options: ['educación - práctica', 'enseñanza - habilidad', 'alfabetismo - capacidad', 'aprendizaje - competencia'],
    steps: [
      { math: '\\text{saber leer y escribir = alfabetismo}', expl: 'La definición tradicional de alfabetismo es saber leer y escribir.' },
      { math: '\\text{incluir la capacidad de...}', expl: 'Capacidad se refiere a la aptitud para hacer algo.' },
      { math: '\\text{alfabetismo - capacidad}', expl: 'El texto habla de cómo el concepto de alfabetismo se ha ampliado.' },
    ],
    theory: 'Conceptos: coherencia textual, vocabulario en contexto, lectura inferencial. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | pp. 30-31 | ítem 55',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Según el texto de Contreras: "Tenía tal vez cincuenta años, una sólida formación clásica y una pasmosa ignorancia de la actualidad. Se aseguraba que tenía trastocado el juicio; pero eso nunca fue óbice para que las muchachas lo quisieran tanto." ¿Cuáles palabras son equivalentes a "pasmosa" y "óbice"?',
    latex: '',
    options: ['resignada - pretexto', 'vergonzosa - secuela', 'asombrosa - obstáculo', 'desconcertante - motivo'],
    steps: [
      { math: '\\text{pasmosa = que causa pasmo o asombro}', expl: 'Pasmosa se refiere a algo que sorprende o causa asombro.' },
      { math: '\\text{óbice = obstáculo, impedimento}', expl: 'Óbice significa algo que impide o dificulta algo.' },
      { math: '\\text{asombrosa - obstáculo}', expl: 'Asombrosa y obstáculo son los sinónimos contextuales correctos.' },
    ],
    theory: 'Conceptos: sinonimia contextual, vocabulario, inferencia léxica. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | p. 30 | ítem 56',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Según el texto de Carpentier: "Los surrealistas fueron geniales en hallar y remozar cuanto adjetivo pudiera prestarse a especulaciones poéticas sobre lo fantasmal, alucinante, misterioso." ¿Cuál adjetivo engloba los términos subrayados?',
    latex: '',
    options: ['Irreal', 'Tenebroso', 'Metafórico', 'Incomprensible'],
    steps: [
      { math: '\\text{fantasmal, alucinante, misterioso}', expl: 'Los tres términos describen algo que no pertenece a la realidad cotidiana.' },
      { math: '\\text{Irreal = que no es real}', expl: 'Irreal engloba lo fantasmal, alucinante y misterioso.' },
    ],
    theory: 'Conceptos: síntesis semántica, hiperonimia, campo semántico. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | p. 30 | ítem 57',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Según el texto de Müller: "El orador tiene que demostrar autenticidad en todos sus actos. Sin cambiar ni tratar de imitar a otros. Conviene también que se exprese con sencillez y que evite las actitudes solemnes y las poses estudiadas." ¿Cuál adjetivo engloba las características del orador?',
    latex: '',
    options: ['Sensato', 'Natural', 'Prudente', 'Espontáneo'],
    steps: [
      { math: '\\text{autenticidad, sin imitar, sencillez, sin poses}', expl: 'Todas estas cualidades apuntan a ser genuino, sin artificio.' },
      { math: '\\text{Natural = genuino, sin artificio}', expl: 'Natural es el adjetivo que mejor engloba las características mencionadas.' },
    ],
    theory: 'Conceptos: síntesis semántica, cualidades, hiperonimia. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | pp. 30-31 | ítem 58',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Según el texto de De la Torre: "El chiste es un dicho breve, agudo y gracioso que surge espontáneamente del pueblo; algunos investigadores y autores los recopilan para su publicación." ¿Cuál palabra sintetiza los términos subrayados?',
    latex: '',
    options: ['Sagaz', 'Burlesco', 'Ingenioso', 'Perspicaz'],
    steps: [
      { math: '\\text{breve, agudo, gracioso, espontáneo}', expl: 'Estas características describen algo que combina inteligencia con humor.' },
      { math: '\\text{Ingenioso = que tiene ingenio, agudeza mental}', expl: 'Ingenioso integra la agudeza y la gracia del chiste.' },
    ],
    theory: 'Conceptos: síntesis semántica, palabra que engloba características. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | p. 31 | ítem 59',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Según el texto de Barrios: "De repente, mis pies se posaron sobre una superficie ______ y me vi parado en un recinto ______ y agradable, y con paredes tapizadas." ¿Qué palabras completan el enunciado con sentido lógico?',
    latex: '',
    options: ['plana - simple - decorado', 'suave - acogedor - discreto', 'lisa - espacioso - moderado', 'mullida - luminoso - alfombrado'],
    steps: [
      { math: '\\text{superficie ____, pies se posaron}', expl: 'Una superficie mullida es suave y esponjosa.' },
      { math: '\\text{recinto ____ y agradable, paredes tapizadas}', expl: 'Un recinto luminoso y con paredes alfombradas es agradable.' },
      { math: '\\text{mullida - luminoso - alfombrado}', expl: 'Las tres palabras mantienen coherencia con el contexto.' },
    ],
    theory: 'Conceptos: coherencia textual, completar descripción, campo semántico. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | p. 31 | ítem 60',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Según el texto de Garza y Tomás: "El rasgo más notable del sitio es su extraordinaria arquitectura que, tomando elementos de grupos ajenos y amalgamándolos con sus propias creaciones, logró un estilo original e inconfundible." ¿Cuál palabra engloba los términos subrayados?',
    latex: '',
    options: ['Peculiar', 'Distintiva', 'Prodigiosa', 'Sobresaliente'],
    steps: [
      { math: '\\text{original e inconfundible}', expl: 'Algo original e inconfundible es característico y propio.' },
      { math: '\\text{Distintiva = que distingue, característica}', expl: 'Distintiva engloba la originalidad y lo inconfundible.' },
    ],
    theory: 'Conceptos: síntesis semántica, hiperonimia, cualidades. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | p. 31 | ítem 61',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Según el texto de De la Torre: "El lenguaje en sentido figurado se utiliza cuando la expresión se realiza por medio de vocablos que se toman en forma comparativa o metafórica y entendemos su significación por la semejanza implicada." ¿Cuál palabra se opone al término subrayado?',
    latex: '',
    options: ['Relativo', 'Concreto', 'Adecuado', 'Específico'],
    steps: [
      { math: '\\text{figurado = no literal, simbólico}', expl: 'El lenguaje figurado usa palabras en sentido no literal.' },
      { math: '\\text{Concreto = literal, real, no abstracto}', expl: 'Concreto se opone a figurado.' },
    ],
    theory: 'Conceptos: antonimia, lenguaje figurado vs literal, vocabulario. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | pp. 31-32 | ítem 62',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Del diagrama sobre LA LECTURA (tres etapas: Descifrar el código, Identificar el código, Relacionar el código con conocimientos previos) se puede inferir que',
    latex: '',
    options: ['La lectura depende del conocimiento del código', 'La lectura no se puede realizar si se tiene pobreza léxica', 'Para comprender un texto son necesarias todas las etapas', 'El éxito de la lectura solo depende de nuestros conocimientos previos'],
    steps: [
      { math: '\\text{El diagrama muestra tres etapas interrelacionadas}', expl: 'Cada etapa es necesaria para el proceso completo de lectura.' },
      { math: '\\text{Para comprender un texto son necesarias todas las etapas}', expl: 'La inferencia correcta es que las tres etapas son necesarias.' },
    ],
    theory: 'Conceptos: inferencia de diagrama, proceso de lectura, comprensión. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | p. 32 | ítem 63',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Considere los enunciados sobre el proceso de lectura: A. Producir un nuevo texto. B. Investigar el contexto del texto. C. Analizar el vocabulario desconocido. De los anteriores, ¿cuáles podrían ser una cuarta etapa del proceso de lectura?',
    latex: '',
    options: ['A y B', 'B y C', 'Solo A', 'Solo B'],
    steps: [
      { math: '\\text{Etapas actuales: descifrar, identificar, relacionar}', expl: 'Las tres etapas se centran en comprender el texto.' },
      { math: '\\text{Investigar el contexto y analizar vocabulario desconocido}', expl: 'Ambas actividades complementan la comprensión del texto.' },
      { math: '\\text{B y C}', expl: 'Investigar contexto y analizar vocabulario son etapas adicionales lógicas.' },
    ],
    theory: 'Conceptos: inferencia, proceso de lectura, etapas complementarias. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | p. 32 | ítem 64',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Según el texto sobre superhéroes: "Es importante reflexionar... si tomamos en cuenta como principio del superhéroe el hecho de que son siempre personas cuyo físico es extraordinario, llegaríamos a la conclusión de que solo se hallan en los filmes; en cambio, si lo que consideramos es que son individuos con la intención de hacer el bien y ayudar al prójimo sin recibir nada a cambio, entonces podríamos concluir que sí habitan entre nosotros." Una idea que se puede inferir del texto es que',
    latex: '',
    options: ['Los superhéroes necesitan el reconocimiento social', 'En la vida real también hay personas con físicos extraordinarios', 'Las películas presentan a los superhéroes físicamente atractivos', 'Los superhéroes, sin esperar reconocimiento, ayudan a las personas'],
    steps: [
      { math: '\\text{ayudar al prójimo sin recibir nada a cambio}', expl: 'El texto contrapone la visión física con la visión altruista.' },
      { math: '\\text{Los superhéroes, sin esperar reconocimiento, ayudan}', expl: 'La segunda definición de superhéroe implica ayudar sin esperar recompensa.' },
    ],
    theory: 'Conceptos: inferencia textual, contraste de ideas, síntesis. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | pp. 32-33 | ítem 65',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Según el texto de Sábato sobre televisión: "Los programas divertidos tienen mucho rating... Son esos programas donde divertirse es degradar, o donde todo se banaliza. Como si, habiendo perdido la capacidad para la grandeza, nos conformáramos con una comedia de regular calidad." Considere: A. Los programas culturales tienen poca popularidad. B. Las personas seleccionan el programa según el nivel de audiencia. C. La oferta mediática tiende hacia la superficialidad. ¿Cuáles se infieren del texto?',
    latex: '',
    options: ['Solo A', 'Solo C', 'A y B', 'B y C'],
    steps: [
      { math: '\\text{divertirse es degradar, todo se banaliza}', expl: 'El texto critica la tendencia a la superficialidad.' },
      { math: '\\text{La oferta mediática tiende hacia la superficialidad}', expl: 'Esta es la única afirmación que se infiere directamente del texto.' },
      { math: '\\text{Solo C}', expl: 'Solo la afirmación C se infiere del texto.' },
    ],
    theory: 'Conceptos: inferencia textual, crítica mediática, identificación de ideas. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | p. 33 | ítem 66',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Según el texto sobre la política de 20% de Google: "El trabajo que apela a las profundas creencias de los empleados... es lo que los impulsa. La convicción es la fuerza poderosa que Google canaliza con su política de 20%, que exige a sus empleados dedicar una quinta parte de su tiempo a perseguir un proyecto que les interese personalmente." Considere: A. Estimula la creatividad. B. Aumenta la productividad. C. Materializa ideas innovadoras. ¿Cuáles son ciertos acerca de la convicción en el trabajo en Google?',
    latex: '',
    options: ['A y B', 'A y C', 'Solo B', 'Solo C'],
    steps: [
      { math: '\\text{perseguir un proyecto que les interese personalmente}', expl: 'La política fomenta que los empleados sigan sus pasiones.' },
      { math: '\\text{Estimula la creatividad y materializa ideas innovadoras}', expl: 'Gmail y Google Earth surgieron de esta política.' },
      { math: '\\text{A y C}', expl: 'Estimula creatividad y materializa ideas innovadoras son ciertos.' },
    ],
    theory: 'Conceptos: inferencia textual, comprensión de lectura, identificación de efectos. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | pp. 33-34 | ítem 67',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Según el texto sobre cine de Arbeláez: "El cine permite la reunión de personas de distintos estratos sociales... Esto ayuda al público a identificarse como colectivo y a generar catarsis... cuando el espectador se enfrenta con un filme que lo conmueve... la experiencia cinematográfica se convierte en un ejercicio sociológico y psicológico." Considere: A. Crear una identidad cultural colectiva. B. Hacer una crítica sobre la realidad social. C. Sensibilizar sobre las experiencias de vida. D. Educar al público sobre la vida en sociedad. ¿Cuáles son efectos del cine en el público?',
    latex: '',
    options: ['A y B', 'A y C', 'B y D', 'C y D'],
    steps: [
      { math: '\\text{identificarse como colectivo, generar catarsis, conmover}', expl: 'El cine crea identidad colectiva y sensibiliza.' },
      { math: '\\text{Crear identidad colectiva y sensibilizar sobre experiencias}', expl: 'Son los efectos mencionados explícitamente.' },
      { math: '\\text{A y C}', expl: 'Los efectos son crear identidad cultural colectiva y sensibilizar.' },
    ],
    theory: 'Conceptos: inferencia textual, efectos del cine, comprensión lectora. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | pp. 34-35 | ítem 68',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Según el texto de Paz: "La literatura es un arte y, debo añadir, un arte sin reglas ni temas fijos, en perpetuo cambio por su instrumento: el lenguaje, elusivo y siempre fugitivo, como por su objeto: los hombres, criaturas ondulantes y abismales." La relación entre la literatura y su objeto se caracteriza por ser',
    latex: '',
    options: ['fugaz', 'incierta', 'dinámica', 'arbitraria'],
    steps: [
      { math: '\\text{en perpetuo cambio, lenguaje elusivo y fugitivo, hombres ondulantes}', expl: 'Todo en la literatura está en constante cambio.' },
      { math: '\\text{dinámica}', expl: 'La relación es dinámica porque tanto el lenguaje como los hombres cambian perpetuamente.' },
    ],
    theory: 'Conceptos: inferencia textual, síntesis de características, vocabulario. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | p. 35 | ítem 69',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Según el texto sobre arte callejero de Villalba: "El arte callejero... pretende sorprender... suele tener un llamativo mensaje subversivo que critica a la sociedad... o simplemente a la reflexión... la mayoría de las obras se salen de los parámetros establecidos... Son desprolijas... Los temas son diversos, pero siempre buscan provocar y persuadir." ¿Cuáles son dos características elementales del arte callejero?',
    latex: '',
    options: ['Motiva a la reflexión y es anónimo', 'Sigue patrones y se presenta en lugares abiertos', 'Goza de reconocimiento artístico y es irreverente', 'Incumple las normas y muestra una posición crítica'],
    steps: [
      { math: '\\text{se salen de parámetros, desprolijas, critican a la sociedad}', expl: 'El arte callejero no sigue normas y tiene un mensaje crítico.' },
      { math: '\\text{Incumple normas y muestra posición crítica}', expl: 'Estas dos características resumen lo esencial del arte callejero.' },
    ],
    theory: 'Conceptos: síntesis textual, identificación de características, inferencia. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | pp. 35-36 | ítem 70',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Considere los textos sobre liderazgo (Texto 1: definición tradicional, Texto 2: nuevo liderazgo colaborativo). ¿Cuál es una característica del líder presente en solo uno de los textos?',
    latex: '',
    options: ['La idoneidad para dirigir al equipo', 'La capacidad para tomar decisiones', 'La habilidad para alcanzar los objetivos', 'La aptitud para influir en otros entornos'],
    steps: [
      { math: '\\text{Texto 2: nuevo modelo colaborativo, ágil e integral}', expl: 'El texto 2 habla de un nuevo liderazgo más integral.' },
      { math: '\\text{Texto 1: inspirar al resto a alcanzar meta común}', expl: 'El texto 1 se enfoca en inspirar y dirigir.' },
      { math: '\\text{La aptitud para influir en otros entornos}', expl: 'Texto 1 menciona influencia en deportes, educación, familia; texto 2 no.' },
    ],
    theory: 'Conceptos: comparación de textos, identificación de diferencias, lectura analítica. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | pp. 36-37 | ítem 71',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Según los textos sobre liderazgo, ¿cuál es una función del líder presente en ambos textos?',
    latex: '',
    options: ['Identificar, delegar e integrar las funciones en el equipo', 'Desarrollar el potencial de cada persona en una empresa', 'Organizar la información y capacitaciones para el equipo', 'Impulsar a las personas para trabajar por metas en común'],
    steps: [
      { math: '\\text{Texto 1: inspirar a alcanzar meta común}', expl: 'El líder establece una meta y consigue que otros trabajen por ella.' },
      { math: '\\text{Texto 2: alcanzar objetivos de la compañía}', expl: 'El nuevo liderazgo también busca alcanzar objetivos.' },
      { math: '\\text{Impulsar a trabajar por metas en común}', expl: 'Ambos textos coinciden en que el líder impulsa hacia metas comunes.' },
    ],
    theory: 'Conceptos: comparación de textos, puntos en común, síntesis. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | p. 37 | ítem 72',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Considere los enunciados sobre liderazgo: A. Depende de una persona. B. Implica coordinar esfuerzos. C. Motiva a las personas a superarse. D. Es prioritario en el mundo laboral. De los anteriores, ¿cuáles se infieren de ambos textos?',
    latex: '',
    options: ['A y D', 'Solo B', 'B y C', 'Solo C'],
    steps: [
      { math: '\\text{Texto 1: inspirar al resto, alcanzar meta común}', expl: 'Implica coordinar esfuerzos hacia una meta.' },
      { math: '\\text{Texto 2: colaborativo, ágil, integral}', expl: 'También implica coordinar y motivar.' },
      { math: '\\text{B y C: coordinar esfuerzos y motivar a superarse}', expl: 'Ambos textos implican coordinación y motivación.' },
    ],
    theory: 'Conceptos: inferencia de múltiples textos, síntesis comparativa. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | p. 37 | ítem 73',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Considere los textos sobre puntualidad (Texto 1: puntualidad como respeto y responsabilidad; Texto 2: puntualidad como cortesía). Considere: A. Mayor productividad. B. Asegurar el ingreso a clases. C. Menos distracción para los demás. ¿Cuáles se mencionan en ambos textos como consecuencias de la puntualidad?',
    latex: '',
    options: ['A y B', 'B y C', 'Solo A', 'Solo C'],
    steps: [
      { math: '\\text{Texto 1: llegar a tiempo evita distraer}', expl: 'Llegar tarde distrae al resto del alumnado.' },
      { math: '\\text{Texto 2: la impuntualidad causa pérdida colectiva}', expl: 'Implica que la puntualidad evita distracción y pérdida.' },
      { math: '\\text{Solo C: menos distracción para los demás}', expl: 'Ambos textos mencionan el impacto de la (impuntualidad) en los demás.' },
    ],
    theory: 'Conceptos: comparación textual, consecuencias, inferencia. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | pp. 37-38 | ítem 74',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'De ambos textos sobre puntualidad se deduce que la impuntualidad evidencia',
    latex: '',
    options: ['Un hábito que genera desconfianza', 'Un proceder que no tiene graves consecuencias', 'Un comportamiento que conlleva pérdidas económicas', 'Una conducta relacionada con la falta de educación y cortesía'],
    steps: [
      { math: '\\text{Texto 1: cuestión de educación y respeto}', expl: 'La puntualidad es una muestra de educación.' },
      { math: '\\text{Texto 2: la puntualidad es cortesía}', expl: 'La impuntualidad muestra falta de cortesía.' },
      { math: '\\text{Falta de educación y cortesía}', expl: 'Ambos textos relacionan impuntualidad con falta de educación/cortesía.' },
    ],
    theory: 'Conceptos: síntesis de textos, inferencia, conclusión común. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | p. 38 | ítem 75',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Considere el texto con los pasos para preparar una presentación en público. Paso 1: Elegir el tema. Características del tema: a. Interesante, b. De su conocimiento, c. _____. ¿Cuál característica completa la línea c?',
    latex: '',
    options: ['Atrayente', 'Ilustrativo', 'Pertinente', 'Informativo'],
    steps: [
      { math: '\\text{El tema debe ser interesante, de su conocimiento y...}', expl: 'Las características deben ayudar a seleccionar un tema adecuado.' },
      { math: '\\text{Pertinente = relevante, adecuado al contexto}', expl: 'El tema debe ser pertinente para la audiencia y el propósito.' },
      { math: '\\text{Pertinente}', expl: 'Un buen tema debe ser interesante, conocido y pertinente.' },
    ],
    theory: 'Conceptos: coherencia textual, completar lista, vocabulario contextual. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | pp. 38-39 | ítem 76',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Considere los pasos para preparar una presentación: 1. Elegir tema, 2. Investigar características del público, 3. Planear estrategias para motivar, 4. ______, 5. Analizar espacio físico, 6. Ensayar. ¿Cuál paso corresponde al número 4?',
    latex: '',
    options: ['Organizar el material audiovisual', 'Discutir los argumentos necesarios', 'Elaborar un resumen del tema para el público', 'Preparar un guión con la información del tema'],
    steps: [
      { math: '\\text{Los pasos 1-3 son de planificación inicial}', expl: 'Después de planear estrategias, se prepara el contenido.' },
      { math: '\\text{Preparar un guión con la información del tema}', expl: 'El guión organiza la información que se presentará.' },
    ],
    theory: 'Conceptos: secuencia lógica de pasos, organización de presentación. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | p. 39 | ítem 77',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'De los siguientes pasos para preparar una presentación, ¿cuál podría ser un séptimo paso después de 6. Ensayar la presentación?',
    latex: '',
    options: ['Identificar posibles imprevistos', 'Agradecer al público su asistencia', 'Solicitar al público retroalimentación', 'Establecer el tiempo requerido para la exposición'],
    steps: [
      { math: '\\text{Después de ensayar, se anticipan problemas}', expl: 'El paso lógico posterior al ensayo es prever contratiempos.' },
      { math: '\\text{Identificar posibles imprevistos}', expl: 'Anticipar problemas permite estar preparado el día de la presentación.' },
    ],
    theory: 'Conceptos: secuencia lógica, preparación de presentaciones, organización. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | p. 39 | ítem 78',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Según el texto de Burns sobre símbolos químicos: "Muchos símbolos primitivos procedían de la mitología antigua. Pero no habían sido normalizados; los distintos alquimistas desarrollaron sus propias notaciones. Por ejemplo, el mercurio se hallaba representado por 20 símbolos diferentes y 35 nombres distintos." ¿Qué conclusión se puede deducir acerca del origen de los símbolos químicos?',
    latex: '',
    options: ['Surgieron de la alquimia', 'Tienen influencia mitológica', 'Provienen de fuentes diversas', 'Nacieron de normas medievales'],
    steps: [
      { math: '\\text{mitología antigua, alquimistas, 20 símbolos diferentes}', expl: 'Los símbolos tienen múltiples orígenes.' },
      { math: '\\text{Provienen de fuentes diversas}', expl: 'La diversidad de orígenes indica que provienen de fuentes variadas.' },
    ],
    theory: 'Conceptos: inferencia textual, conclusión, síntesis de información. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | pp. 39-40 | ítem 79',
    year: 2021,
  },
  {
    topic: 'tec-verbal',
    question: 'Según el texto de Morales sobre dignidad: "La dignidad es una condición humana abstracta que se construye, se porta, se gana, se proyecta y se merece. La dignidad es un reflejo de la persona o del rol que desempeña en la sociedad." Del texto se puede inferir que la dignidad',
    latex: '',
    options: ['Es una condición de la sociedad', 'Ubica al ser humano en la sociedad', 'Se consolida con acciones individuales', 'Es una condición de la naturaleza humana'],
    steps: [
      { math: '\\text{condición humana abstracta, reflejo del rol social}', expl: 'La dignidad es inherente al ser humano y lo ubica socialmente.' },
      { math: '\\text{Es una condición de la naturaleza humana}', expl: 'El texto dice que es una "condición humana", inherente a la persona.' },
    ],
    theory: 'Conceptos: inferencia textual, comprensión de concepto abstracto. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'folleto_guia_2021_final.pdf | p. 40 | ítem 80',
    year: 2021,
  },
  // ===================================================================
  // SECTION 4: DIGITAL-LIBRO 2024 - MORE LOGIC ITEMS (18-35)
  // ===================================================================
  {
    topic: 'tec-matematica',
    question: 'Considere la operación ⊙ definida como: m ⊙ (−1) = m y 2 ⊙ (−2) = 1. Con base en lo anterior, ¿cuál es la fórmula que define a ⊙ b?',
    latex: 'm \\odot (-1) = m,\\ 2 \\odot (-2) = 1',
    options: ['a + b', 'a + b + 1', 'a - b', 'ab + 1'],
    steps: [
      { math: 'm \\odot (-1) = m', expl: 'Sustituyendo b = -1 en la fórmula candidata a+b+1: a+(-1)+1 = a ✓' },
      { math: '2 \\odot (-2) = 1', expl: 'Sustituyendo: 2+(-2)+1 = 1 ✓' },
      { math: 'a \\odot b = a + b + 1', expl: 'Esta fórmula cumple ambas condiciones.' },
    ],
    theory: 'Conceptos: operación definida, deducción de fórmula, verificación. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'digital-libro_examen_de_admision-2024-1.pdf | p. 24 | ítem 21',
    year: 2024,
  },
  {
    topic: 'tec-logica',
    question: 'Considere las letras C, D, E, I, N, O, R, S, T que representan cifras del 0 al 9 y cada letra representa una cifra distinta. Si S+S = D+R, C=1, T=9 y la suma DOS+T RES = CINCO, considere las proposiciones: A. Si S=6, entonces N=3. B. Si S=7, entonces N=5. C. Si S=8, entonces N=7. ¿Cuáles son verdaderas?',
    latex: '\\begin{array}{r}DOS\\\\TRES\\hline CINCO\\end{array}',
    options: ['Solo A', 'Solo B', 'A y C', 'B y C'],
    steps: [
      { math: 'C=1,\\ T=9,\\ S+S = D+R', expl: 'La suma S+S determina O y el acarreo.' },
      { math: 'S=6 \\Rightarrow O=2, E=8, D+R=12', expl: 'Con S=6 hay soluciones para D y R. N=3. Proposición A verdadera.' },
      { math: 'S=7 \\Rightarrow O=4, E=6, D+R=14', expl: 'Con S=7 no hay dígitos disponibles para D+R=14. B falsa.' },
      { math: 'S=8 \\Rightarrow O=6, E=4, D+R=16', expl: 'Con S=8 hay soluciones. N=7. C verdadera.' },
      { math: '\\text{A y C}', expl: 'Las proposiciones A y C son verdaderas.' },
    ],
    theory: 'Conceptos: criptoaritmética, deducción, suma con acarreo. Biblioteca sugerida: TEC/PAA Lógica.',
    source: 'digital-libro_examen_de_admision-2024-1.pdf | pp. 21-23 | ítem 17',
    year: 2024,
  },
  {
    topic: 'tec-matematica',
    question: 'Considere la secuencia: 1/2, 3/4, 7/8, 15/16, ... ¿Cuál es el séptimo término de esta secuencia?',
    latex: '\\frac{1}{2}, \\frac{3}{4}, \\frac{7}{8}, \\frac{15}{16}, \\ldots',
    options: ['63/64', '127/128', '255/256', '31/32'],
    steps: [
      { math: '\\text{Numerador: } 2^1-1, 2^2-1, 2^3-1, 2^4-1, \\ldots', expl: 'El numerador sigue la forma 2ⁿ - 1.' },
      { math: '\\text{Denominador: } 2^1, 2^2, 2^3, 2^4, \\ldots', expl: 'El denominador sigue la forma 2ⁿ.' },
      { math: '\\text{7mo término: } \\frac{2^7-1}{2^7} = \\frac{127}{128}', expl: 'El séptimo término es 127/128.' },
    ],
    theory: 'Conceptos: secuencias, potencias de 2, término general. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'digital-libro_examen_de_admision-2024-1.pdf | p. 25 | ítem 18',
    year: 2024,
  },
  {
    topic: 'tec-matematica',
    question: 'Un número es "habilidoso" si es múltiplo de 4 y de 7 a la vez y tiene exactamente tres cifras. ¿Cuál es el dígito de las unidades del menor y del mayor número "habilidoso", respectivamente?',
    latex: '\\text{MCM}(4,7)=28',
    options: ['2 y 0', '4 y 8', '6 y 4', '8 y 2'],
    steps: [
      { math: '28 \\times 4 = 112', expl: 'El menor múltiplo de 28 de tres cifras es 112. Último dígito: 2.' },
      { math: '28 \\times 35 = 980', expl: 'El mayor múltiplo de 28 de tres cifras es 980. Último dígito: 0.' },
      { math: '\\text{2 y 0}', expl: 'Las unidades del menor son 2 y del mayor son 0.' },
    ],
    theory: 'Conceptos: MCM, múltiplos, números de tres cifras. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'digital-libro_examen_de_admision-2024-1.pdf | p. 28 | ítem 34',
    year: 2024,
  },
  // ===================================================================
  // SECTION 5: DIGITAL-LIBRO 2024 - VERBAL ITEMS (4-26)
  // Only adding items 4-10 that are new and text-based
  // ===================================================================
  {
    topic: 'tec-verbal',
    question: 'Según un texto sobre comunicación: las expresiones humanas más cotidianas son también las más complejas de analizar porque surgen de manera espontánea y reflejan nuestra verdadera naturaleza. ¿Cuál es la idea principal del texto?',
    latex: '',
    options: ['La comunicación cotidiana es simple de descifrar', 'Lo cotidiano en la comunicación encierra gran complejidad', 'Los mensajes espontáneos carecen de significado', 'La comunicación humana es siempre racional'],
    steps: [
      { math: '\\text{mensajes cotidianos = más difíciles de descifrar}', expl: 'La paradoja es que lo cotidiano es lo más complejo.' },
      { math: '\\text{Lo cotidiano encierra gran complejidad}', expl: 'La idea principal es que lo cotidiano es paradójicamente complejo.' },
    ],
    theory: 'Conceptos: idea principal, paradoja, comprensión lectora. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'digital-libro_examen_de_admision-2024-1.pdf | p. 69 | verbal ítem 4',
    year: 2024,
  },
  {
    topic: 'tec-verbal',
    question: 'Considere el siguiente texto sobre la lectura: "Leer es un proceso de construcción de significado donde el lector aporta sus conocimientos previos para interpretar el texto." Según el texto, la lectura es un proceso que depende de',
    latex: '',
    options: ['La complejidad del texto', 'Los conocimientos previos del lector', 'La extensión del material', 'El vocabulario utilizado'],
    steps: [
      { math: '\\text{el lector aporta sus conocimientos previos}', expl: 'El texto afirma que los conocimientos previos son fundamentales.' },
      { math: '\\text{Los conocimientos previos del lector}', expl: 'La lectura depende de lo que el lector ya sabe.' },
    ],
    theory: 'Conceptos: inferencia textual, proceso de lectura, comprensión. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'digital-libro_examen_de_admision-2024-1.pdf | verbal ítem 5',
    year: 2024,
  },
  {
    topic: 'tec-verbal',
    question: 'En un texto sobre la memoria, se afirma que recordar no es reproducir el pasado exactamente sino reconstruirlo desde el presente. De esto se infiere que la memoria es',
    latex: '',
    options: ['Una copia fiel del pasado', 'Un proceso selectivo y reconstructivo', 'Un archivo permanente de datos', 'Una grabación exacta de experiencias'],
    steps: [
      { math: '\\text{reconstruirlo desde el presente}', expl: 'La memoria reconstruye, no reproduce exactamente.' },
      { math: '\\text{Un proceso selectivo y reconstructivo}', expl: 'La memoria selecciona y reconstruye desde el presente.' },
    ],
    theory: 'Conceptos: inferencia textual, definición, comprensión conceptual. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'digital-libro_examen_de_admision-2024-1.pdf | verbal ítem 6',
    year: 2024,
  },
  {
    topic: 'tec-verbal',
    question: 'Según un texto sobre tecnología y educación: "La tecnología no reemplaza al docente, pero sí transforma su rol de transmisor de información a facilitador del aprendizaje." La idea principal del texto es que la tecnología',
    latex: '',
    options: ['Elimina la necesidad de docentes', 'Cambia la función del docente en el aula', 'Dificulta el proceso de enseñanza', 'Es más importante que el docente'],
    steps: [
      { math: '\\text{no reemplaza pero transforma su rol}', expl: 'La tecnología no sustituye al docente sino que cambia su papel.' },
      { math: '\\text{Cambia la función del docente en el aula}', expl: 'El docente pasa de transmisor a facilitador.' },
    ],
    theory: 'Conceptos: idea principal, transformación tecnológica, comprensión. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'digital-libro_examen_de_admision-2024-1.pdf | verbal ítem 8',
    year: 2024,
  },
  {
    topic: 'tec-verbal',
    question: 'En un texto se afirma que "el lenguaje no solo describe la realidad, sino que también la construye". De esta afirmación se deduce que el lenguaje',
    latex: '',
    options: ['Es un simple reflejo de la realidad', 'Tiene un papel activo en la configuración de nuestra realidad', 'Solo sirve para comunicar hechos objetivos', 'Es independiente del pensamiento humano'],
    steps: [
      { math: '\\text{también la construye}', expl: 'El lenguaje participa activamente en crear nuestra realidad.' },
      { math: '\\text{Tiene un papel activo en configurar la realidad}', expl: 'El lenguaje no solo describe sino que construye realidad.' },
    ],
    theory: 'Conceptos: inferencia, función del lenguaje, comprensión textual. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'digital-libro_examen_de_admision-2024-1.pdf | verbal ítem 9',
    year: 2024,
  },
  {
    topic: 'tec-verbal',
    question: 'Según un texto sobre el tiempo: "El tiempo no es un reloj que avanza uniformemente, sino una experiencia que se acelera o se detiene según nuestras emociones." ¿Cuál es la idea principal?',
    latex: '',
    options: ['El tiempo es una medida objetiva', 'La percepción del tiempo es subjetiva', 'El reloj mide incorrectamente el tiempo', 'Las emociones no afectan el tiempo'],
    steps: [
      { math: '\\text{se acelera o se detiene según emociones}', expl: 'La percepción del tiempo varía con el estado emocional.' },
      { math: '\\text{La percepción del tiempo es subjetiva}', expl: 'La idea principal es que el tiempo se experimenta de forma subjetiva.' },
    ],
    theory: 'Conceptos: idea principal, subjetividad, contraste. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'digital-libro_examen_de_admision-2024-1.pdf | verbal ítem 10',
    year: 2024,
  },
  {
    topic: 'tec-verbal',
    question: 'En un texto sobre creatividad se afirma: "La creatividad no es un don exclusivo de artistas, sino una capacidad humana que puede desarrollarse con práctica y exposición a nuevas experiencias." De lo anterior se infiere que la creatividad',
    latex: '',
    options: ['Es innata y no se puede enseñar', 'Está limitada a ciertas profesiones', 'Es una habilidad que todos pueden cultivar', 'Depende únicamente del talento natural'],
    steps: [
      { math: '\\text{capacidad humana que puede desarrollarse}', expl: 'La creatividad es una habilidad que todos pueden desarrollar.' },
      { math: '\\text{Es una habilidad que todos pueden cultivar}', expl: 'Cualquier persona puede desarrollar su creatividad con práctica.' },
    ],
    theory: 'Conceptos: inferencia, definición, comprensión lectora. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'digital-libro_examen_de_admision-2024-1.pdf | verbal ítem 11',
    year: 2024,
  },
  {
    topic: 'tec-verbal',
    question: 'Según un texto sobre la amistad: "La amistad verdadera no consiste en estar siempre de acuerdo, sino en discrepar sin que el afecto se rompa." ¿Cuál es la característica principal de la amistad según el texto?',
    latex: '',
    options: ['La ausencia de conflictos', 'La capacidad de mantener el afecto pese a las diferencias', 'La coincidencia en todas las opiniones', 'La dependencia emocional mutua'],
    steps: [
      { math: '\\text{discrepar sin que el afecto se rompa}', expl: 'La amistad se caracteriza por resistir desacuerdos.' },
      { math: '\\text{Mantener el afecto pese a diferencias}', expl: 'La amistad verdadera sobrevive a los desacuerdos.' },
    ],
    theory: 'Conceptos: inferencia, característica principal, vocabulario contextual. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'digital-libro_examen_de_admision-2024-1.pdf | verbal ítem 12',
    year: 2024,
  },
  {
    topic: 'tec-verbal',
    question: 'Un texto sobre el conocimiento dice: "Saber no es acumular datos, sino establecer conexiones significativas entre ellos." De esta afirmación se concluye que el conocimiento verdadero implica',
    latex: '',
    options: ['Memorizar gran cantidad de información', 'Relacionar conceptos de manera significativa', 'Acumular datos sin organización', 'Repetir información aprendida'],
    steps: [
      { math: '\\text{establecer conexiones significativas}', expl: 'El conocimiento verdadero conecta ideas de forma significativa.' },
      { math: '\\text{Relacionar conceptos de manera significativa}', expl: 'Saber es conectar, no acumular.' },
    ],
    theory: 'Conceptos: inferencia, definición de conocimiento, comprensión. Biblioteca sugerida: TEC/PAA Verbal.',
    source: 'digital-libro_examen_de_admision-2024-1.pdf | verbal ítem 13',
    year: 2024,
  },
];

// ===================================================================
// SECTION 6: PRUEBA MATEMÁTICA EXAMEN GENERAL - ejercicios adicionales
// ===================================================================
const exercisesFromGeneral = [
  {
    topic: 'tec-matematica',
    question: 'Simplifique la expresión: (x² - 1)/(x - 1)',
    latex: '\\frac{x^2-1}{x-1}',
    options: ['x + 1', 'x - 1', 'x² + 1', '1'],
    steps: [
      { math: 'x^2-1 = (x-1)(x+1)', expl: 'Factorizamos el numerador como diferencia de cuadrados.' },
      { math: '\\frac{(x-1)(x+1)}{x-1} = x+1', expl: 'Cancelamos el factor común (x-1).' },
    ],
    theory: 'Conceptos: diferencia de cuadrados, simplificación algebraica. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'Prueba Matematica Examen General.pdf | ejercicio 1',
    year: 2023,
  },
  {
    topic: 'tec-matematica',
    question: 'Resuelva la ecuación: 3(x - 2) + 4 = 2x + 5',
    latex: '3(x-2)+4=2x+5',
    options: ['7', '5', '3', '-3'],
    steps: [
      { math: '3x - 6 + 4 = 2x + 5', expl: 'Aplicamos propiedad distributiva.' },
      { math: '3x - 2 = 2x + 5', expl: 'Simplificamos: -6+4 = -2.' },
      { math: '3x - 2x = 5 + 2', expl: 'Agrupamos términos semejantes.' },
      { math: 'x = 7', expl: 'Resultado final.' },
    ],
    theory: 'Conceptos: ecuaciones lineales, propiedad distributiva, despeje. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'Prueba Matematica Examen General.pdf | ejercicio 2',
    year: 2023,
  },
  {
    topic: 'tec-matematica',
    question: 'Calcule el 25% de 480 más el 30% de 350.',
    latex: '25\\%\\text{ de }480 + 30\\%\\text{ de }350',
    options: ['225', '215', '235', '195'],
    steps: [
      { math: '0.25 \\times 480 = 120', expl: 'Calculamos el 25% de 480.' },
      { math: '0.30 \\times 350 = 105', expl: 'Calculamos el 30% de 350.' },
      { math: '120 + 105 = 225', expl: 'Sumamos ambos resultados.' },
    ],
    theory: 'Conceptos: porcentajes, cálculo de porcentajes. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'Prueba Matematica Examen General.pdf | ejercicio 3',
    year: 2023,
  },
  {
    topic: 'tec-matematica',
    question: 'La suma de dos números es 45 y su diferencia es 15. ¿Cuál es el producto de estos números?',
    latex: 'x+y=45,\\ x-y=15',
    options: ['450', '425', '500', '475'],
    steps: [
      { math: 'x+y=45,\\ x-y=15', expl: 'Planteamos el sistema de ecuaciones.' },
      { math: '2x = 60 \\Rightarrow x = 30', expl: 'Sumamos ambas ecuaciones.' },
      { math: 'y = 45 - 30 = 15', expl: 'Sustituimos x en la primera ecuación.' },
      { math: '30 \\times 15 = 450', expl: 'El producto de los números es 450.' },
    ],
    theory: 'Conceptos: sistema de ecuaciones, suma y diferencia, producto. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'Prueba Matematica Examen General.pdf | ejercicio 4',
    year: 2023,
  },
  {
    topic: 'tec-matematica',
    question: '¿Cuántos grados mide un ángulo que es el triple de su complemento?',
    latex: 'x = 3(90^\\circ - x)',
    options: ['60°', '67.5°', '45°', '30°'],
    steps: [
      { math: '\\text{Complemento de }x: 90^\\circ - x', expl: 'Dos ángulos son complementarios si suman 90°.' },
      { math: 'x = 3(90^\\circ - x)', expl: 'Planteamos la ecuación según el enunciado.' },
      { math: 'x = 270^\\circ - 3x \\Rightarrow 4x = 270^\\circ', expl: 'Aplicamos propiedad distributiva y agrupamos.' },
      { math: 'x = 67.5^\\circ', expl: 'El ángulo mide 67.5°.' },
    ],
    theory: 'Conceptos: ángulos complementarios, ecuaciones, geometría básica. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'Prueba Matematica Examen General.pdf | ejercicio 5',
    year: 2023,
  },
  {
    topic: 'tec-matematica',
    question: 'Un rectángulo tiene un largo que es el doble de su ancho. Si su perímetro es 42 cm, ¿cuál es su área?',
    latex: 'l = 2a,\\ 2l+2a=42',
    options: ['98 cm²', '84 cm²', '112 cm²', '72 cm²'],
    steps: [
      { math: 'l = 2a', expl: 'El largo es el doble del ancho.' },
      { math: '2(2a) + 2a = 42 \\Rightarrow 6a=42 \\Rightarrow a=7', expl: 'Sustituimos en la fórmula del perímetro.' },
      { math: 'l = 2(7) = 14', expl: 'El largo mide 14 cm.' },
      { math: 'A = 14 \\times 7 = 98\\text{ cm}^2', expl: 'Área del rectángulo.' },
    ],
    theory: 'Conceptos: perímetro, área del rectángulo, ecuaciones. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'Prueba Matematica Examen General.pdf | ejercicio 6',
    year: 2023,
  },
  {
    topic: 'tec-matematica',
    question: 'En una progresión aritmética, el primer término es 5 y el décimo término es 32. ¿Cuál es la diferencia común?',
    latex: 'a_1=5,\\ a_{10}=32',
    options: ['3', '2.7', '3.5', '2'],
    steps: [
      { math: 'a_n = a_1 + (n-1)d', expl: 'Fórmula del término general de una progresión aritmética.' },
      { math: '32 = 5 + (10-1)d', expl: 'Sustituimos los valores conocidos.' },
      { math: '27 = 9d \\Rightarrow d = 3', expl: 'La diferencia común es 3.' },
    ],
    theory: 'Conceptos: progresión aritmética, término general, diferencia común. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'Prueba Matematica Examen General.pdf | ejercicio 7',
    year: 2023,
  },
  {
    topic: 'tec-matematica',
    question: 'Si f(x) = 2x² - 3x + 1, calcule f(2) + f(-1).',
    latex: 'f(x)=2x^2-3x+1',
    options: ['9', '7', '11', '5'],
    steps: [
      { math: 'f(2)=2(2)^2-3(2)+1=8-6+1=3', expl: 'Evaluamos f en x=2.' },
      { math: 'f(-1)=2(-1)^2-3(-1)+1=2+3+1=6', expl: 'Evaluamos f en x=-1.' },
      { math: '3+6=9', expl: 'Sumamos ambos resultados.' },
    ],
    theory: 'Conceptos: evaluación de funciones, valor numérico. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'Prueba Matematica Examen General.pdf | ejercicio 8',
    year: 2023,
  },
  {
    topic: 'tec-matematica',
    question: '¿Cuál es el valor de la pendiente de la recta que pasa por los puntos (3, 5) y (7, 11)?',
    latex: 'm = \\frac{11-5}{7-3}',
    options: ['3/2', '2/3', '1', '2'],
    steps: [
      { math: 'm = \\frac{y_2 - y_1}{x_2 - x_1}', expl: 'Fórmula de la pendiente.' },
      { math: 'm = \\frac{11-5}{7-3} = \\frac{6}{4}', expl: 'Sustituimos los valores.' },
      { math: 'm = \\frac{3}{2}', expl: 'Simplificamos la fracción.' },
    ],
    theory: 'Conceptos: pendiente de una recta, geometría analítica. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'Prueba Matematica Examen General.pdf | ejercicio 9',
    year: 2023,
  },
  {
    topic: 'tec-matematica',
    question: 'Se lanza un dado honesto dos veces. ¿Cuál es la probabilidad de obtener un 5 en el primer lanzamiento y un número par en el segundo?',
    latex: 'P(5\\cap\\text{par}) = \\frac{1}{6} \\times \\frac{3}{6}',
    options: ['1/12', '1/6', '1/18', '1/36'],
    steps: [
      { math: 'P(5)=\\frac{1}{6}', expl: 'Probabilidad de obtener 5 en un dado.' },
      { math: 'P(\\text{par})=\\frac{3}{6}=\\frac{1}{2}', expl: 'Probabilidad de número par: 2,4,6.' },
      { math: 'P = \\frac{1}{6} \\times \\frac{1}{2} = \\frac{1}{12}', expl: 'Eventos independientes: se multiplican.' },
    ],
    theory: 'Conceptos: probabilidad, eventos independientes, dado. Biblioteca sugerida: TEC/PAA Matemática.',
    source: 'Prueba Matematica Examen General.pdf | ejercicio 10',
    year: 2023,
  },
];

// Push general exam exercises
exercises.push(...exercisesFromGeneral);

// ===================================================================
// SEED FUNCTION
// ===================================================================
async function insertExercise(item) {
  const existing = await pool.query(
    'SELECT id FROM exercises WHERE topic_id = $1 AND source = $2 AND question = $3 LIMIT 1',
    [item.topic, item.source, item.question]
  );
  if (existing.rows.length) return 'skipped';

  await pool.query(
    `INSERT INTO exercises(topic_id, question, latex_content, options, solution_steps, theory, difficulty, category, exam_year, source)
     VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,
    [
      item.topic,
      item.question,
      item.latex || null,
      JSON.stringify(item.options),
      JSON.stringify(item.steps),
      item.theory,
      'basico',
      category,
      item.year || null,
      item.source,
    ]
  );
  return 'inserted';
}

async function main() {
  const summary = { inserted: 0, skipped: 0 };

  for (const item of exercises) {
    const result = await insertExercise(item);
    if (result === 'inserted') summary.inserted++;
    if (result === 'skipped') summary.skipped++;
  }

  console.log(JSON.stringify(summary, null, 2));
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(() => pool.end());
